/* Welcome GF · 8 Emails · Day 0 → Day 21
   Voice: warm, peer-to-peer, validation-first, symptom-language only
   Generated by sub-agents per blueprint + plan
*/

window.FLOW_WELCOME_GF = window.FLOW_WELCOME_GF || {};

// ═══════════════════════════════════════════════════════════════
// EMAIL 1
// ═══════════════════════════════════════════════════════════════
// welcome-01-e1-gf . content copy data
// Plain copy fields, referenced by emails.jsx via window.FLOW_WELCOME_GF.e1

window.FLOW_WELCOME_GF.e1 = {
  subject: "Your child might not feel the signal",
  preheader: "Whether they're 3 or 10, verbal or non-verbal, if they don't feel when they need to go, here's why.",
  day: 0,
  level: "General Family",

  // Part badge / hero
  partBadge: "Day 0 \u00b7 Welcome",
  heroBadge: "Welcome to BrightKidCo",
  h1a: "Your child might not feel the",
  h1b: "signal",
  heroSubhead: "Whether they're 3 or 10, verbal or non-verbal, if they don't feel when they need to go, here's why.",

  // Section 1 . opening letter
  letter1First: "Whether your child is just starting to show signs, or you've been at this for years with every method you can find online, if they don't feel when they need to go, this why.\n\nYou've tried what the books said. What the internet told you. What well-meaning friends suggested: sticker charts, timer sits, the 3-day method, pull-ups that promised an straightforward transition. You tried them all with hope. And none of them worked the way they were supposed to.\n\nThat's not because you did something wrong. It's because every one of those methods assumes your child can feel the \"I need to go\" signal.",
  letter1Paras: [
    "If your child's nervous system processes body signals differently, and for many children it does, those methods couldn't work. Not because you weren't consistent enough. Not because your child isn't \"ready.\"",
    "Here's what parents tell us every day:",
    "\u201cHe doesn't have full bladder awareness yet.\u201d",
    "\u201cShe'll pee herself and just keep playing in the puddle.\u201d",
    "\u201cPotty training isn't linear.\u201d",
    "\u201cI feel like a failure because he's still in pull-ups.\u201d",
    "You're not a failure. The problem isn't motivation or behavior. It's neurology.",
    "Research shows that many children have what's called an interoception gap, the feeling of a full bladder simply doesn't arrive in time. The signal between body and brain travels on a different frequency (Nicholson et al. 2019)."
  ],

  // Section 2 . the mechanism
  h2Mechanism: "The mechanism, what the science actually shows",
  letter2First: "Research shows that 49% of autistic 4-5 year olds aren't toilet trained yet \u2013 a 6-to-1 gap compared to typically developing kids. That's not a parenting gap. It's a measurable neurological difference in how body signals are processed.",
  letter2Paras: [
    "The brain-body connection that tells most people \u201cI need to go\u201d works differently for your child. But this gap can be addressed \u2013 interoception, the ability to sense internal body states, can be trained with the right approach.",
    "The question isn't \u201cwill my child ever get this?\u201d",
    "The question is: \u201cwhat does my child need for their brain to start receiving the signal?\u201d"
  ],

  // Section 3 . the product
  letter3First: "At BrightKidCo, we designed something different. Not a training method that asks your child to feel something they can't. Not another book or system that assumes the signal is already there.",
  letter3Paras: [
    "We designed underwear that creates the signal, a gentle sensation that lasts that gives your child's brain something to connect to.",
    "Our 3-layer Body-Signal Learning System:",
    "Cotton inner layer designed for sensitive skin, soft against nervous systems that process fabric differently",
    "Smart absorption core, protects surfaces without wicking away the wetness signal that the brain needs to learn",
    "Gentle outer barrier, leak-resistant without creating the \u201ctoo dry\u201d problem that pull-ups cause",
    "The science is one-step but powerful: the brain learns through feedback. When the feedback is absent (pull-ups keep your child too dry) or delayed (cotton underwear floods all at once), learning can't happen. Our system creates the right kind of feedback, sustained enough for the brain to register."
  ],

  // Section 4 . product showcase
  productName: "Body-Signal Training Pant",
  productImage: "product-photos/flat-lay/training-pant-bunny-hearts-pink.jpg",
  productPrice: "Single pair from \u20ac24",

  // Section 5 . testimonials
  letter4First: "What other parents found.",
  letter4Paras: [
    "\u201cThese past three years have been hell. We tried literally everything. I was ready to give up.\u201d \u2013 GF parent, early 30s, child 5",
    "\u201cI absolutely lost it. I yelled at him and smacked his butt. Then I cried for an hour because I felt like a monster. That's when I realized something was wrong with the method, not with him.\u201d \u2013 GF parent, late 30s, child 4",
    "\u201cHe does great at ABA but won't go near the potty at home. I knew it wasn't defiance, but I couldn't figure out what it was.\u201d \u2013 GF parent, child 6",
    "Each of these parents thought they were the only one. Each of them discovered the same thing: their child's body wasn't sending the signal they assumed was there."
  ],

  // Section 6 . 60 day try
  h2Try: "Try it for 60 days. Your judgment.",
  letter5First: "You don't have to believe me. Try it for 60 days. If your child shows any sign of awareness, a pause, a look, a step toward the potty, you'll know the signal is working. If nothing changes, full refund. Your judgment.",
  letter5Paras: [
    "Days 1\u201330: notice the first signal. A pause, a look, a shift.",
    "Days 31\u201360: the gap starts closing. The signal arrives earlier.",
    "After 60: keep it, or send it back. We refund the full purchase, no forms."
  ],

  // Section 7 . keep reading + CTA
  h2KeepReading: "Keep reading",
  letter6First: "If this sounds familiar, keep reading. We'll send you more over the next few days, what the science says, what other parents found, and how you can try the Body-Signal approach.",
  letter6Paras: [
    "Primary CTA: If You're Ready to Explore \u2192 See How It Works",
    "Next time: Why the methods you tried couldn't work \u2013 and what actually can."
  ],

  ctaButton: "See How It Works",
  ctaIntro: "Whenever you're ready.",
  ctaFinePrint: "60 days. Full refund. No forms.",

  // Images
  heroImage: "product-photos/lifestyle/toddler-livingroom-dino-yellow.png",
  heroAlt: "Toddler in the living room. The signal that tells them they need to go is missing.",
  mechanismImage: "product-photos/flat-lay/training-pant-fox-red-white.jpg",
  mechanismAlt: "Training pant flat lay. The Body-Signal Learning System that creates the wetness signal pull-ups block.",

  // Signoff / closing
  signoffName: "BKC team",
  closingWord: "Talk soon"
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 2
// ═══════════════════════════════════════════════════════════════
// welcome-01-e2-gf · content copy data
// Plain copy fields . referenced by emails.jsx via window.FLOW_WELCOME_GF.e2

window.FLOW_WELCOME_GF.e2 = {
  subject: "Why sticker charts fail some kids",
  preheader: "The real reason rewards, timers, and schedules couldn't work, explained in plain language",
  day: 1,
  level: "General Family",

  // Part badge / hero
  partBadge: "✿ Email two of eight",
  heroBadge: "✿ Email two of eight",
  h1a: "Why sticker charts",
  h1b: "fail some kids",
  heroSubhead: "The real reason rewards, timers, and schedules couldn't work, explained in plain language",

  // Hero image (position 5)
  heroImage: "product-photos/lifestyle/toddler-livingroom-dino-yellow.png",
  heroAlt: "Toddler playing calmly in a warm living room setting, in BrightKidCo body-signal learning pants, no clinical context",
  heroLabel: "HERO · THE SIGNAL STARTS BEFORE THE METHOD",
  heroSublabel: "Circular crop, teal frame. A child in a normal moment of play. No bathroom, no clinical setting. Ratio 1:1, 240px desktop / 160px mobile",
  heroShadow: 6,

  // Section 1 . opening letter with 4px emerald left border (position 6)
  letter1First: "Whether your child is 3 or 10, verbal or non-verbal, diagnosed or wondering, if they don't feel when they need to go, every method that assumes they do will fail.",
  letter1Paras: [
    "You've tried what the books and the internet told you. Sticker charts. Reward jars. Timer sits. The \"naked weekend.\" Maybe scheduled sits every 30 minutes. And none of it changed the core problem.",
    "That's not because you didn't try hard enough. It's because every one of those methods assumed something that isn't true for your child's nervous system."
  ],

  // Section 2 . MechanismDef (position 8)
  mechanismEyebrow: "THE WORD",
  mechanismTitle: "Interoception.",
  mechanismTitleAccent: "Interoception",
  mechanismBodyLead: "The internal sense of what's happening inside your body. For children with sensory differences, the signal from bladder to brain can be delayed or absent.",
  mechanismBodyParas: [
    "There's a word for this: interoception. It's the internal sense of what's happening inside your body. Like knowing you're hungry before you feel hangry. Or that you're thirsty before your mouth goes dry. Or, and this is the one that matters, that your bladder is full, a few seconds before it's too late.",
    "For neurotypical kids, this signal usually comes online somewhere between 18 and 30 months. For many neurodivergent children, it develops differently. Sometimes later. Sometimes unevenly. Sometimes the signal is there, but it reaches the brain at the same time the accident is already happening."
  ],
  mechanismStatNumber: "49%",
  mechanismStatLabel: "of autistic 4-5 year olds aren't toilet trained yet",
  mechanismStatCompare: "Wiggins et al. 2022 (CDC-funded, N=743). That's not a parenting failure. It suggests a measurable gap in how the body sends and receives signals.",
  mechanismStatCitation: "Wiggins et al. 2022 · Nicholson et al. 2019",

  // Section 3 . Mid-body inline breaker (position 9)
  inlineImage2: "product-photos/lifestyle/toddler-potty-ladder-yellow-woodland.png",
  inlineAlt2: "Toddler in BrightKidCo pants standing near a yellow woodland potty ladder, a calm mid-body moment",
  inlineLabel2: "MECHANISM · THE PATHWAY THE METHODS MISSED",
  inlineSublabel2: "Mid-body inline breaker. The child is in the same space as the potty, not yet on it. The signal has room to arrive. Ratio ~4:3",
  inlineShadow2: 3,

  // Section 4 . FailedMethodsGrid (position 10)
  failedIntroEyebrow: "WHY NOTHING WORKED",
  failedIntroTitle: "You can't reward a signal that isn't reaching the brain yet.",
  failedIntroBody: "Sitting on the potty for 20 minutes and having nothing happen. The reward chart with a full row of stickers, and still no progress. \"He knows he has to go, he just won't.\" I hear versions of this story from parents every single day.",
  failedCards: [
    {
      label: "REWARDS",
      icon: "✕",
      iconColor: "#C84B3B",
      header: "Sticker charts. Reward jars.",
      body: "Rewards require awareness. For a child whose signal arrives late, the connection between action and reward never lands."
    },
    {
      label: "TIMERS",
      icon: "✕",
      iconColor: "#C84B3B",
      header: "Timer sits every 20-30 minutes.",
      body: "Timers teach a schedule, not a signal. Your child learns to comply, or to resist, but not to feel."
    },
    {
      label: "NAKED METHOD",
      icon: "✕",
      iconColor: "#C84B3B",
      header: "The \"naked weekend.\"",
      body: "The naked method gives you accidents without a feedback loop the brain can learn from. Chaos doesn't teach. It dysregulates."
    },
    {
      label: "BODY-SIGNAL APPROACH",
      icon: "✓",
      iconColor: "#039902",
      header: "Works with the signal, not against it.",
      body: "Meets your child's nervous system where it actually is. The signal becomes the curriculum, not the schedule."
    }
  ],

  // Section 5 . Guide breaker (position 11)
  inlineImage3: "product-photos/accessories/book-potty-training-guide.png",
  inlineAlt3: "The BrightKidCo potty training guide book, a small supportive reference for parents",
  inlineLabel3: "THE GUIDE THAT GOES WITH THIS EMAIL",
  inlineSublabel3: "A small accessory, a companion object. Not the hero, a quiet invitation. Ratio ~4:3",
  inlineShadow3: 3,

  // CTA inline (NOT CTAClose primitive)
  ctaIntro: "The difference between a method that works and one that doesn't isn't motivation or effort. It's whether the method meets your child where their nervous system actually is.",
  ctaIntroSecondary: "Tomorrow, I'll walk through how a different approach, built around the signal itself, not around a schedule, changes the equation.",
  ctaButton: "See how body-signal learning works",
  ctaHref: "https://www.brightkidco.com/pages/body-signal-learning",
  ctaFinePrint: "No rush, read when you're ready.",
  ctaNextTime: "Next time: The research behind the body-signal approach, and why 49% of children face this gap.",

  // Signoff (Lena Bauer short variant)
  psLines: [
    "P.S. If you want to see how the body-signal approach works, here's a gentle explanation. No pressure.",
    "P.S. I've been where you are. Take your time."
  ],

  // Signoff / closing
  signoffName: "Lena Bauer",
  closingWord: "Talk soon"
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 3
// ═══════════════════════════════════════════════════════════════
// welcome-01-e3-gf · content copy data
// Plain copy fields — referenced by emails.jsx via window.FLOW_WELCOME_GF.e3
//
// 49% SPARK stat email — Validation → Stat normalization → Mechanism clarity → Cautious hope
// 3-family triptych + 49% stat callout + 3-layer mechanism explainer + 3 testimonials
// 2 Letters combined into one content blob per blueprint (validation+mechanism+3-layer
// in letter1Paras; testimonials+product+guarantee+offer+ps in letter2Paras)

window.FLOW_WELCOME_GF.e3 = {
  subject: "Almost 1 in 2 kids this age isn't trained",
  preheader: "The science behind why traditional potty training fails some children, and what actually works.",
  day: 3,
  level: "General Family",

  // Title block / hero
  heroBadge: "Day 3 \u00b7 The Signal",
  h1a: "The signal that",
  h1b: "arrives",
  heroSubhead: "Three parents, three different kids, one common experience.",

  // Part badge (49% tilted sticker, positioned over the hero)
  partBadgeText: "49%",
  partBadge: "49%",

  // Three-family triptych (3 FramedImage cards, each a different family voice)
  socialProof: [
    {
      alt: "Family quote card 1: He talks about the potty. He understands the concept. But when it's time to actually go, nothing.",
      wash: "#F5F0EB",
      shadow: 6,
    },
    {
      alt: "Family quote card 2: We've done the OT sensory work, the BCBA protocol, the social stories, the sticker charts. We are stuck.",
      wash: "#EEF3ED",
      shadow: 4,
    },
    {
      alt: "Family quote card 3: He's never shown a single sign of feeling wet or dirty. Not once in all these years.",
      wash: "#F0EEF5",
      shadow: 3,
    },
  ],

  // Stat callout (49% breakout) — FramedImage with ImgFrame placeholder
  stat: {
    number: "49%",
    label: "49%",
    sublabel: "CDC-funded study, 743 children (Wiggins et al. 2022) \u00b7 8% typically developing \u00b7 6:1 gap",
    citation: "Wiggins et al. 2022 \u00b7 Nicholson et al. 2019",
    shadow: 6,
  },

  // Letter 1 — validation + mechanism + 3-layer explainer
  letter1First: "Here's what the research actually shows: 49% of autistic 4-5 year olds are not yet toilet trained.",
  letter1Paras: [
    "That's not a made-up number. That's from a CDC-funded study of 743 children (Wiggins et al. 2022). Compare that to 8% of typically developing kids of the same age, and the gap is 6:1.",
    "Thisn't happening because you didn't try hard enough. It's happening because the methods assume something that isn't true for your child: that they can feel when they need to go.",
    "Whether your child is 3 or 10, verbal or non-verbal, newly diagnosed or still figuring it out, if they don't feel the \"I need to go\" signal, every method that assumes they do will struggle.",
    "Every sticker chart and timer sit assumes your child feels the sensation of a full bladder. But research consistently shows many autistic children have a measurable difference in interoception \u2014 the eighth sensory system that tells the brain when we're hungry, thirsty, or need the bathroom.",
    "The signal from bladder to brain is delayed or absent. It's not defiance. It's neurology. And here's the part that matters: interoception can be trained. The childhood window is the intervention opportunity.",
    "The 3-Layer System:",
    "1. Cotton Inner Layer \u2014 Creates a gentle, sustained \"uh-oh\" sensation when wet. Not a shock, not an alarm. A 30-60 second window of feedback that gives a nervous system that picks up signals slowly time to register: something happened.",
    "2. Smart Absorption Core \u2014 Protects furniture, floors, and clothes without wicking the wetness signal away like a pull-up does. It's the difference between \"too dry to feel\" and \"there's a signal your brain can learn from.\"",
    "3. Leak-Resistant Outer Barrier \u2014 Made for real life. Playgrounds. Car seats. Grandma's couch. Because you shouldn't have to choose between body awareness and mess-free days.",
    "Thisn't a pull-up replacement. It's a learning tool, designed for the brain that learns differently.",
  ],

  // Letter 2 — testimonials + product + guarantee + CTA offer + PS line
  letter2First: "\"He said 'I need to pee' AFTER it's already happened for two years. After two weeks in BrightKidCo underwear, he paused. Then he looked down. Then he walked to the potty. It was small, maybe nothing to someone else. But that never happened before.\"",
  letter2Paras: [
    ", Mom of a 5-year-old, Level 2",
    "\"I was skeptical. We'd tried everything. But the 60-day guarantee made me feel safe trying. Week three, she stopped in the middle of playing and touched her underwear. She didn't make it to the bathroom that time. But she FELT it.\"",
    ", Mom of a 4-year-old, Level 1",
    "\"In 9 years, he never once showed awareness of being wet. After a month in these, he looked down. He paused. That was huge for us.\"",
    ", Mom of a 9-year-old, Level 3",
    "BrightKidCo isn't training underwear in the traditional sense. It's a Body-Signal Learning System built around one principle: the brain needs feedback to learn.",
    "60 days. By your judgment.",
    "If it doesn't help your child make progress, if you don't see a pause, a look down, a single step toward the bathroom, full refund. No forms. No \"did you try hard enough.\" Your judgment is the only metric that matters.",
    "Start with the 3+3 Bundle, \u20ac79.99",
    "6 pairs of Body-Signal Learning underwear. Free shipping. 60-day guarantee.",
    "Whether you're just starting to explore or you've been at this for years, the bundle covers enough pairs to rotate through laundry cycles while your child's brain builds the connection.",
    "Or start with 1 pair (\u20ac34.99) if you want to try before committing.",
    "That's \u20ac13.33 per pair with the bundle \u2014 less than half the single-pair price.",
    "Next time: How the Body-Signal Learning Layer works \u2014 and why it's different from everything you've tried.",
  ],

  // 60-Day Guarantee inline circular seal + 3-dot color-coded checkmark cards
  guaranteeLabel: "60 days. By your judgment.",
  guaranteeSub: "If it doesn't help your child make progress, full refund. No forms. Your judgment is the only metric that matters.",
  guaranteePoints: [
    { title: "60 full days. By your judgment.", body: "Not 30 \u2014 because nervous systems don't work on a 30-day calendar. 60 is the window where you'll see whether the feedback loop is starting to form." },
    { title: "Full refund if it isn't the right fit.", body: "No forms. No \"did you try hard enough.\" A pause, a look down, a single step toward the bathroom \u2014 your judgment is the only metric that matters." },
    { title: "Regressions are part of the process.", body: "If your child has a setback inside the 60 days, the guarantee still applies. Setbacks are often the step right before a real change." },
  ],

  // 3+3 bundle (primary) + 1 pair (secondary)
  offer: {
    primary: {
      label: "3+3 Bundle",
      price: "\u20ac79.99",
      note: "6 pairs of Body-Signal Learning underwear \u00b7 Free shipping \u00b7 60-day guarantee",
      cta: "Start with the 3+3 Bundle",
      href: "#",
    },
    secondary: {
      label: "Single pair",
      price: "\u20ac34.99",
      note: "Try before committing \u00b7 \u20ac13.33 per pair with the bundle",
      cta: "Or start with 1 pair",
      href: "#",
    },
  },

  // 3-layer explainer (rendered as numbered list inside the Letter — feeds the inline rendering)
  threeLayer: [
    {
      n: "1",
      name: "Cotton Inner Layer",
      body: "Creates a gentle, sustained \"uh-oh\" sensation when wet. Not a shock, not an alarm. A 30-60 second window of feedback that gives a nervous system that picks up signals slowly time to register: something happened.",
    },
    {
      n: "2",
      name: "Smart Absorption Core",
      body: "Protects furniture, floors, and clothes without wicking the wetness signal away like a pull-up does. It's the difference between \"too dry to feel\" and \"there's a signal your brain can learn from.\"",
    },
    {
      n: "3",
      name: "Leak-Resistant Outer Barrier",
      body: "Made for real life. Playgrounds. Car seats. Grandma's couch. Because you shouldn't have to choose between body awareness and mess-free days.",
    },
  ],

  // Images (FramedImage src paths)
  family1Image: "product-photos/lifestyle/toddler-livingroom-dino-yellow.png",
  family2Image: "product-photos/lifestyle/toddler-outdoors-grass-disposable-diaper.png",
  family3Image: "product-photos/lifestyle/toddler-napping-watermelon-pink-shorts.png",

  // CTA
  ctaButton: "Start with the 3+3 Bundle",
  ctaIntro: "Whenever you're ready.",
  ctaFinePrint: "60 days \u00b7 \u20ac79.99 \u00b7 Free shipping \u00b7 Your judgment, your pace.",

  // Signoff / closing
  signoffName: "Lena Bauer",
  closingWord: "With understanding",
  psLine: "Next time: How the Body-Signal Learning Layer works \u2014 and why it's different from everything you've tried.",

  // Footer
  footerAddress: "BrightKidCo Ltd \u00b7 Berlin, Germany \u00b7 hello@brightkidco.com",
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 4
// ═══════════════════════════════════════════════════════════════
// welcome-01-e4-gf · content copy data
// Plain copy fields — referenced by emails.jsx via window.FLOW_WELCOME_GF.e4

window.FLOW_WELCOME_GF.e4 = {
  subject: "Three kids, three stories, one thing in common",
  preheader: "Whether your child is 3 or 10, verbal or non-verbal, diagnosed or still figuring it out, these three families all found the same thing.",
  day: 7,
  level: "General Family",

  // Part badge / hero
  partBadge: "Part 1 of 3 \u00b7 Day 7",
  heroBadge: "Part 1 of 3 \u00b7 Day 7",
  h1a: "Three kids.",
  h1b: "One thing.",
  subhead: "Three different families. Three different stories. One thing in common.",

  // Section 1 — opening letter (warm cream)
  letter1First: "Whether your child is just starting to show signs, or you're years into what feels like every possible method, if they don't feel when they need to go, you've been fighting the wrong battle.",
  letter1Paras: [
    "I hear from parents every day who are exhausted, out of ideas, and wondering if this will ever click. Let me introduce you to three families. Three different kids. Three completely different stories. One thing in common."
  ],

  // Section 2 — testimonial triptych (3 cards)
  triptychIntro: "Three different families. Three different kids. One thing in common.",
  triptychCards: [
    {
      label: "FAMILY 1",
      border_color: "#E8A98F",
      avatar_color: "#F2C9B6",
      quote: "My son talks about the potty but won't actually do it. He says 'I need to pee' AFTER it's already happened. We'd been stuck for over a year. After about 3 weeks in these undies, he paused mid-accident. Looked down. Then walked to the potty. That pause, that had never happened before.",
      by: "Parent of a 4-year-old, mostly verbal, mild sensory differences"
    },
    {
      label: "FAMILY 2",
      border_color: "#8AB9B5",
      avatar_color: "#B6D4D1",
      quote: "We'd tried everything from the BCBA's protocol to OT sensory work to social stories. Scheduled sits for 2 years, he never went on his own. We didn't expect a product to solve it. But the wetness signal in these undies is different, he can actually feel it. After 6 weeks, he initiated once. Once! After 4 years of nothing.",
      by: "Parent of a 6-year-old, mixed verbal, moderate support needs"
    },
    {
      label: "FAMILY 3",
      border_color: "#D4B886",
      avatar_color: "#E5D2AD",
      quote: "He's never shown a sign of feeling wet or dry, not once in 9 years. We'd made peace with maybe never. After 8 weeks in the body-signal underwear, he paused. He felt something. That was everything.",
      by: "Parent of a 9-year-old, non-verbal, high support needs"
    }
  ],

  // Section 3 — second letter (soft mint)
  letter2First: "If any of these sound familiar, your child's nervous system isn't broken. It's just not getting the information it needs.",
  letter2Paras: [
    "If you've ever thought any of these things, you're not alone. You haven't failed. You've been working with advice that wasn't built for your child's nervous system.",
    "I feel like we have tried everything, reward systems, punishments and nothing seems to work. Real parent.",
    "I feel like a failure because he's still in pull ups. Real parent.",
    "Nearly half of autistic 4-5 year olds, 49%, are still not toilet trained (Wiggins et al. 2022, CDC-funded study of 743 children). That's compared to just 8% of typically developing children the same age.",
    "That statistic doesn't mean something is wrong with your child. It means what you're going through is documented, measurable, and far more common than you think."
  ],

  // Mechanism inline breaker
  mechanismImage: "product-photos/lifestyle/toddler-potty-ladder-yellow-woodland.png",
  mechanismAlt: "Toddler in BrightKidCo pants near a potty ladder, the body-signal learning moment",
  mechanismLabel: "MECHANISM \u00b7 THE BODY-SIGNAL BRIDGE",
  mechanismSublabel: "Mid-body inline breaker showing a child beginning to register the body signal. Ratio ~4:3",

  // Section 4 — mechanism letter (continues soft mint)
  letter3First: "Here's what all three families have in common: their children weren't getting the body signal.",
  letter3Paras: [
    "Interoception, the eighth sensory system, is how your brain knows when you're hungry, thirsty, or need the bathroom. For children with sensory processing differences, this signal is delayed, weakened, or absent. Research confirms this is a real, measurable neurological difference.",
    "The Body-Signal Learning Layer creates that feedback, a gentle sensation that lasts 30-60 seconds after every accident. Enough time for the brain to register: something happened."
  ],

  // Section 5 — product showcase
  productLabel: "The product",
  productTitle: "Body-Signal Learning Layer.",
  productTitleAccent: "One pair at a time.",
  productSub: "PFAS-free. BPA-free. Designed alongside OT practitioners who understand sensory processing.",
  productPriceFrom: "\u20ac79.99",
  productPriceNote: "3+3 Bundle \u00b7 6 pairs \u00b7 free shipping \u00b7 60-day guarantee",
  productCta: "Start with the 3+3 Bundle",
  productFeatures: [
    { icon: "\u25c9", label: "Body-Signal Layer\u2122" },
    { icon: "\u2713", label: "60-day guarantee" },
    { icon: "\u2661", label: "Sensory-friendly cotton" }
  ],
  productAgeRange: "Ages 2-10",
  productMicroTrust: "Free shipping on the 3+3 Bundle \u00b7 60-day guarantee \u00b7 Real returns, no forms",

  // Section 6 — guarantee block
  guaranteeLabel: "The 60-day guarantee",
  guaranteeHeadline: "60 days.",
  guaranteeHeadlineAccent: "By your judgment.",
  guaranteeSub: "If your child shows any sign of awareness, a pause, a look, a step toward the bathroom, you'll know the signal is working. If nothing changes, full refund. No questions.",
  guaranteeSealNumber: "60",
  guaranteeSealLabel: "Calm Days",
  guaranteeSealRing: "Calm Progress \u00b7 No Questions \u00b7 Real Returns \u00b7 Sixty Full Days",
  guaranteePoints: [
    {
      title: "Try it for 60 full days.",
      body: "Wear the Body-Signal Learning Layer on the normal routine. Watch for the small signs.",
      color: "#8AB9B5"
    },
    {
      title: "Any sign of awareness counts.",
      body: "A pause, a look, a step toward the bathroom. That's the signal working. That's enough.",
      color: "#D4B886"
    },
    {
      title: "Full refund, no questions.",
      body: "If nothing changes, email us. We refund you. No forms, no proof of progress required.",
      color: "#E8A98F"
    }
  ],

  // Section 7 — closing CTA
  ctaIntro: "The 3+3 Bundle gives you 6 pairs with free shipping, enough coverage to see real body-signal learning happen. If you'd rather try first, the 1-Pair option lets you add alongside your current routine. That's \u20ac13.33 per pair with the bundle, less than half the single-pair price.",
  ctaButton: "Start with the 3+3 Bundle \u2192",
  ctaFinePrint: "Next time: Real stories from parents who've been exactly where you are.",

  // Images
  heroImage: "product-photos/lifestyle/toddler-livingroom-dino-yellow.png",
  heroAlt: "Toddler playing comfortably at home in BrightKidCo body-signal learning pants",
  productMainImage: "product-photos/flat-lay/training-pant-fox-woodland-white.jpg",
  productSecondaryImage: "product-photos/flat-lay/training-pant-watermelon-pink.jpg",

  // Signoff / closing
  signoffName: "Lena Bauer",
  closingWord: "With understanding"
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 5
// ═══════════════════════════════════════════════════════════════
// welcome-01-e5-gf · content copy data
// Plain copy fields — referenced by emails.jsx via window.FLOW_WELCOME_GF.e5
//
// Objection handling: tried everything / hopes up / too old or too severe
// 3 ObjectionCalloutTriptych cards (border-left brand-green #039902)
// + 3 Letter copies (hook / reframe / mechanism + product intro)
// + 1 FramedImage (hero) + 1 FramedImage (mid-body inline breaker)
// + TestimonialPair (2 quote cards + stat strip)
// + ProductShowcaseFull (2 product image slots)
// + GuaranteeBlock (60-day circular seal + 3 checkmark cards)
// + CustomCTA (inline CTA button on dark ink)

window.FLOW_WELCOME_GF.e5 = {
  subject: "If this is another letdown, here's the difference",
  preheader: "You've tried. It didn't work. That's not failure, that's a signal your methods were aimed at the wrong target.",
  day: 10,
  level: "General Family",

  // Part badge / hero
  partBadge: "Part 5 of 8 \u00b7 Day 10",
  heroBadge: "Part 5 of 8 \u00b7 Day 10",
  h1a: "The method failed you.",
  h1b: "The mechanism won't.",
  heroSubhead: "Three objections you've probably asked. Three direct answers. Then, if you're still with me, the reason the mechanism is different.",

  // Section 1 — Hero framed image (position 6)
  heroImage: "product-photos/lifestyle/toddler-napping-watermelon-pink-shorts.png",
  heroAlt: "Parent reading on a couch while a toddler naps nearby, reflective quiet moment",
  heroLabel: "HERO \u00b7 THE PARENT WHO'S ALREADY TRIED EVERYTHING",
  heroSublabel: "Reflective, not action-driven. A pause between attempts. Sensory-friendly palette, warm and quiet. Ratio ~4:3",
  heroShadow: 6,

  // Section 2 — Opening letter (warm cream)
  letter1First: "You've tried. Maybe one method. Maybe 40. Sticker charts, timer sits, rewards, naked weekends, the book everyone swears by, the OT's recommendations, the BCBA's protocol. Nothing changed.",
  letter1Paras: [
    "You're not alone in that. The most common phrase we hear from parents? \"I've tried everything.\"",
    "And when you've heard that from yourself enough times, a new email promising something different doesn't feel hopeful. It feels like setup for another disappointment."
  ],

  // Section 3 — ObjectionCalloutTriptych (3 cards, border-left #039902 brand green)
  objectionIntro: "Let me name the three questions sitting in the back of your mind, because I've asked every single one of them myself:",
  objectionBorderColor: "#039902",
  objectionBorderWidth: 4,
  objectionCards: [
    {
      label: "OBJECTION 1",
      header: "\"I've tried everything. Why would this be different?\"",
      body: "Because every method you tried assumed your child can feel the \"I need to go\" signal. Research shows that for many children whose nervous systems process body signals differently, that signal doesn't arrive in time, or at all (Nicholson et al. 2019)."
    },
    {
      label: "OBJECTION 2",
      header: "\"What if I get my hopes up again?\"",
      body: "That fear is earned. Every product promises. Every method disappoints. I've been there, both my sons went through this. My older one was almost 8 before he trained. So I don't say this lightly: this isn't about hoping. It's about giving your child's nervous system the information it's been missing."
    },
    {
      label: "OBJECTION 3",
      header: "\"Is my child too old, or too severely affected, for this to work?\"",
      body: "Whether your child is 3 or 10, verbal or non-verbal, diagnosed or still wondering, if they don't feel when they need to go, the mechanism addresses the gap, not the label."
    }
  ],

  // Section 4 — Reframe letter (soft mint)
  letter2First: "The reason nothing worked isn't that you didn't try hard enough. It's that every method assumed the signal exists.",
  letter2Paras: [
    "Pull-ups keep kids completely dry, which means the one feedback the brain needs never arrives. Sticker charts depend on body awareness many children don't yet possess. You weren't fighting the wrong battle, you were fighting the right battle with the wrong tools."
  ],

  // Section 5 — Mid-body inline breaker (soft mint)
  mechanismImage: "product-photos/lifestyle/toddler-potty-ladder-pink-multicolor.png",
  mechanismAlt: "Toddler in BrightKidCo body-signal pants standing near a potty ladder, the feedback moment",
  mechanismLabel: "MECHANISM \u00b7 THE FEEDBACK THAT STARTS LEARNING",
  mechanismSublabel: "Mid-body inline breaker: child registers the gentle uh-oh sensation. Ratio ~4:3",
  mechanismShadow: 3,

  // Section 6 — Mechanism letter (soft mint)
  letter3First: "This is where BrightKidCo is different. The body-signal underwear doesn't require your child to feel anything they don't already feel. It creates the sensation.",
  letter3Paras: [
    "Three layers, one purpose: Layer 1, soft cotton that creates a gentle \"uh-oh\" sensation when wet. Layer 2, smart absorption that protects without wicking the signal away. Layer 3, leak-resistant outer barrier that contains the mess.",
    "When your child wears them: Child pees. Feels a gentle, sustained \"uh-oh\". Brain registers: something happened. Over time, the brain learns to recognize the signal before the event.",
    "Research shows interoception can be improved with targeted intervention. The Body-Signal Learning Layer creates the conditions for that training to happen naturally.",
    "This isn't about turning every bathroom moment into a learning exercise. It's about creating a consistent 30-60 second feedback window, every single time your child has an accident. The repetition is what teaches the brain. Pull-ups, by contrast, give zero feedback."
  ],

  // Section 7 — TestimonialPair (2 quote cards + stat strip)
  testimonialQuotes: [
    {
      quote: "After 3 years of nothing, not even a pause, he looked down at the wet spot. First time. It was two seconds. But it was something.",
      by: "Real parent review, BKC customer"
    },
    {
      quote: "I was skeptical. Another product. Another promise. But after 2 weeks, he walked to the bathroom. Not consistently. But he DID it. That never happened before.",
      by: "Real parent review, BKC customer"
    }
  ],
  testimonialStat: "16,511 reviews. 4.9 stars. Not because every child trains overnight, but because for the first time, something is happening. Even if it's small.",

  // Section 8 — Product intro letter (warm cream)
  letter4First: "The 3+3 Bundle gives you 6 pairs of Body-Signal Learning Underwear, enough for a full rotation so your child gets consistent, daily feedback. Cotton inner, smart absorption core, leak-resistant outer. 60-day guarantee. Free shipping.",
  letter4Paras: [
    "Or start with 1 pair (\u20ac34.99) to see if it works for your child before committing to more. No pressure either way."
  ],

  // Section 9 — ProductShowcaseFull
  productLabel: "THE 3+3 BUNDLE",
  productTitle: "Try the 3+3 Bundle.",
  productTitleAccent: "60 days, your judgment.",
  productSub: "6 pairs, full rotation, daily feedback. Cotton inner, smart absorption, leak-resistant outer.",
  productPriceFrom: "\u20ac34",
  productPriceNote: "\u20ac79.99 for 3+3 bundle \u00b7 Free shipping \u00b7 60-day guarantee",
  productCta: "Try the 3+3 Bundle, \u20ac79.99 \u2192",
  productFeatures: [
    { icon: "\u25c9", label: "Body-Signal Layer\u2122" },
    { icon: "\u2713", label: "60-day guarantee" },
    { icon: "\u2661", label: "Sensory-friendly cotton" }
  ],
  productAgeRange: "Ages 2-10",
  productMicroTrust: "Free shipping on the 3+3 Bundle \u00b7 60-day guarantee \u00b7 Real returns, no forms",
  productMainImage: "product-photos/flat-lay/training-pant-watermelon-pink.jpg",
  productSecondaryImage: "product-photos/flat-lay/training-pant-bunny-hearts-pink.jpg",

  // Section 10 — GuaranteeBlock
  guaranteeLabel: "60-DAY GUARANTEE",
  guaranteeHeadline: "The 60-Day Guarantee.",
  guaranteeHeadlineAccent: "60 days.",
  guaranteeSub: "You don't have to believe me. 60 days to try. If your child shows no sign of body awareness, no pause, no look, no step toward the bathroom, full refund. No questions. The guarantee isn't a sales tactic. It's the only honest thing to offer when the outcome depends on your child's nervous system.",
  guaranteeSealNumber: "60",
  guaranteeSealLabel: "Calm Days",
  guaranteeSealRing: "Calm Progress \u00b7 No Questions \u00b7 Real Returns \u00b7 Sixty Full Days",
  guaranteePoints: [
    {
      title: "Try it for 60 full days.",
      body: "Wear the Body-Signal Learning Layer on the normal routine. Watch for the small signs.",
      color: "#8AB9B5"
    },
    {
      title: "Any sign of awareness counts.",
      body: "A pause, a look, a step toward the bathroom. That's the signal working. That's enough.",
      color: "#D4B886"
    },
    {
      title: "Full refund, no questions.",
      body: "If nothing changes, email us. We refund you. No forms, no proof of progress required.",
      color: "#E8A98F"
    }
  ],

  // Section 11 — CustomCTA (inline CTA on dark ink)
  ctaIntro: "See if the 3+3 Bundle closes the gap, 60 days, your judgment. Or start with 1 pair (\u20ac34.99) to see if it works for your child before committing to more. No pressure either way.",
  ctaButton: "Try the 3+3 Bundle, \u20ac79.99",
  ctaButtonArrow: "\u2192",
  ctaHref: "https://www.brightkidco.com/collections/all-products",
  ctaFinePrint: "Or start with 1 pair (\u20ac34.99). Free shipping. 60-day guarantee. That's \u20ac13.33 per pair with the bundle, less than half the single-pair price.",
  ctaPsLine: "Next time: Why pull-ups might be the one thing holding your child back.",

  // Signoff / closing
  signoffName: "Lena Bauer",
  signoffClosing: "With understanding",

  // Footer
  footerAddress: "BrightKidCo, 123 Commerce Street, Suite 200, Nashville, TN 37201"
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 6
// ═══════════════════════════════════════════════════════════════
// welcome-01-e6-gf · content copy data
// Plain copy fields — referenced by emails.jsx via window.FLOW_WELCOME_GF.e6
//
// Pull-Ups Reframe "Too dry to learn." — Day 14 · Part 6 of 8
// 1 PartBadge + StatCallout hero + TitleBlock + 2 Letters (hook / validation)
// + ComparisonCards (2-col Pull-Ups vs BrightKidCo) + H2 + mechanism Letter
// + ProductShowcaseMedium + FramedImage inline breaker + closing Letter
// (testimonials + guarantee + CTA + PS) + Signoff + Footer

window.FLOW_WELCOME_GF.e6 = {
  subject: "The \u20ac50/month product keeping them too dry",
  preheader: "The moisture-wicking tech parents pay a premium for might be the exact thing preventing progress.",
  day: 14,
  level: "General Family",

  // Part badge / hero
  partBadge: "Day 14 \u00b7 Part 6 of 8",
  heroBadge: "Day 14 \u00b7 Part 6 of 8",
  h1a: "Too dry",
  h1b: "to learn.",
  heroSubhead: "The moisture-wicking tech parents pay a premium for might be the exact thing preventing progress.",

  // StatCallout hero (inline JSX, not a primitive)
  statNumber: "\u20ac50 to \u20ac100+",
  statUnit: "/month",
  statLabel: "what parents pay for pull-ups",
  statSublabel: "ongoing, on the thing that might be blocking the signal",

  // Section 1 — Hook letter (warm cream)
  letter1First: "Whether your child has been in pull-ups for three months or three years, if they never seem to notice when they're wet, there's a reason for that.",
  letter1Paras: [
    "And it's probably not what you think.",
    "Pull-ups are designed to keep kids completely dry. That's literally their job. But here's the catch: that moisture-wicking technology parents pay a premium for, \u20ac50 to \u20ac100+ every single month, was built for neurotypical kids who can already feel the \"I need to go\" signal. For those kids, staying dry during training is a helpful feature.",
    "For your child? It might be the very thing keeping them stuck."
  ],

  // Section 2 — ComparisonCards (2-col Pull-Ups vs BrightKidCo)
  comparisonEyebrow: "SIDE BY SIDE",
  comparisonTitle: "Same diaper aisle. Opposite outcome.",
  comparisonSubtitle: "Same goal, completely different feedback loop.",
  comparisonLeftTitle: "Pull-Ups",
  comparisonLeftIcon: "\u2715",
  comparisonLeftBorder: "#C84B3B",
  comparisonLeftHeaderBg: "#FAECE7",
  comparisonRightTitle: "BrightKidCo",
  comparisonRightIcon: "\u2713",
  comparisonRightBorder: "#039902",
  comparisonRightHeaderBg: "#E1F5EE",
  comparisonRows: [
    { leftLabel: "Wetness signal", leftValue: "Completely dry, zero learning signal", rightLabel: "Wetness signal", rightValue: "Gentle \"uh-oh\" sensation, awareness builds" },
    { leftLabel: "Cost", leftValue: "\u20ac50 to \u20ac100+ every month, ongoing", rightLabel: "Cost", rightValue: "\u20ac34.99/pair, one-time investment" },
    { leftLabel: "Feel", leftValue: "Diaper feel, \"baby mode\"", rightLabel: "Feel", rightValue: "Real underwear, big kid pride" },
    { leftLabel: "Effect on learning", leftValue: "Blocks neurological feedback loop", rightLabel: "Effect on learning", rightValue: "Activates body-brain connection" }
  ],

  // Section 3 — Validation letter (warm cream)
  letter2First: "The wetness signal is the only feedback your child's brain can use to learn body awareness. Research shows autistic children process internal body signals differently, the \"I need to go\" feeling either arrives too late or doesn't register at all (Nicholson et al., 2019). The CDC-funded SPARK study found that 49% of autistic 4-5 year olds aren't toilet trained yet (Wiggins et al., 2022).",
  letter2Paras: [
    "That's not a parenting failure. That's a measurable neurological gap.",
    "Pull-ups remove the one piece of feedback the brain needs. They wick moisture away so effectively that your child stays \"too dry to learn.\" The signal that should teach the body-brain connection never arrives.",
    "\"She'll pee herself and just keep playing in the puddle. It's like she doesn't care AT ALL.\", Real parent",
    "She does care. Her brain just isn't getting the message."
  ],

  // Section 4 — Mechanism FramedImage (3-layer system visual)
  mechanismImage: "product-photos/flat-lay/training-pant-cloud-raindrop-white.jpg",
  mechanismAlt: "Body-Signal Training Pant in cloud-raindrop white, the 3-layer system that creates the wetness signal pull-ups block",
  mechanismLabel: "MECHANISM \u00b7 THE 3-LAYER SYSTEM",
  mechanismSublabel: "Product close-up showing cotton inner, smart absorption core, leak-resistant outer barrier",

  // Section 5 — Section H2 heading
  h2Mechanism: "The 3-Layer Body-Signal Learning System",

  // Section 6 — Mechanism letter (soft mint, with 3-layer numbered list inside)
  letter3First: "The body-signal underwear works opposite to pull-ups.",
  letter3Paras: [
    "Instead of wicking moisture away, the inner cotton layer creates a gentle, sustained awareness, a soft \"uh-oh\" sensation that lasts 30-60 seconds after every accident. Just noticeable enough that the brain can finally register: Something happened. I felt it.",
    "This the feedback loop pull-ups were silently blocking.",
    "The 3-Layer Body-Signal Learning System:",
    "1. Inner Cotton. Gentle \"uh-oh\" sensation. Teaches the brain: \"this what wet feels like\".",
    "2. Smart Absorption. Absorbs 3x more than regular undies. Protects without blocking awareness.",
    "3. Protective Barrier. Leak-resistant outer layer. Saves furniture & clothes.",
    "BrightKidCo costs a fraction of what you're spending on disposables every month. And it's doing the opposite of what pull-ups do: it's teaching, not hiding."
  ],

  // Section 7 — ProductShowcaseMedium
  productName: "Body-Signal Training Pant",
  productImage: "product-photos/flat-lay/training-pant-fox-red-white.jpg",
  productPriceLabel: "3+3 Bundle \u20ac79.99 \u00b7 60-day guarantee \u00b7 Free shipping",

  // Section 8 — Mid-body inline breaker FramedImage
  breakerImage: "product-photos/lifestyle/toddler-rearview-cat-mustard.png",
  breakerAlt: "Toddler playing in BrightKidCo body-signal underwear, a calm moment where the signal has room to arrive",
  breakerLabel: "REAL LIFE \u00b7 THE SIGNAL GETS A CHANCE TO LAND",
  breakerSublabel: "Mid-body inline breaker, ratio ~4:3",

  // Section 9 — Closing letter (testimonials + guarantee + CTA + PS, all in one)
  letter4First: "\"She started doing better once I eased up on the stressing out about her not getting it.\", Lynne C., real parent",
  letter4Paras: [
    "\"Potty training isn't linear. Some days are great. Others aren't. That's not starting over, that's how learning happens.\", From our community",
    "This the honest part: every child's nervous system is different. Some kids show first awareness in 2 weeks. For others it takes 8 weeks or more. Both are normal.",
    "That's why the 60-Day Guarantee exists. Try the Body-Signal approach for 60 days. If you see any sign of awareness, a pause, a look down, a step toward the potty, you'll know the signal is working. If nothing changes, full refund. Your judgment.",
    "You don't have to believe me. You just have to try.",
    "Try the Body-Signal approach for 60 days. By your judgment. \u2192 Shop the 3+3 Bundle, \u20ac79.99, Free Shipping",
    "That's \u20ac13.33 per pair with the bundle, less than half the single-pair price.",
    "Next time: Your decision. What to do next, with no pressure."
  ],

  // Inline CTA (dark ink, lime button)
  ctaButton: "Shop the 3+3 Bundle, \u20ac79.99",
  ctaButtonArrow: "\u2192",
  ctaHref: "https://www.brightkidco.com/collections/all-products",

  // Signoff / closing
  signoffName: "Lena Bauer",
  closingWord: "With care",

  // Footer
  footerAddress: "BrightKidCo, 123 Commerce Street, Suite 200, Nashville, TN 37201"
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 7
// ═══════════════════════════════════════════════════════════════
// welcome-01-e7-gf · content copy data
// Plain copy fields — referenced by emails.jsx via window.FLOW_WELCOME_GF.e7
//
// Day 17 · Mechanism — How body-signal learning actually works
// Hook letter → FramedImage (validation hero breaker) → Validation letter (4px
// Warm Amber left-border) → Eyebrow + H2 anchors → Mechanism lead letter →
// LayerRow (3-layer explainer: Signal Creation / Smart Absorption / Leak-Resistant
// Barrier) → Mechanism metaphor closer letter → Eyebrow + TestimonialQuintet
// (5 mini-win cards, alternating left/right indent) → Testimonials closing letter
// → FramedImage product hero → ProductShowcaseFull (2 product image slots) →
// Product bullets letter → GuaranteeBlock (60-day seal + 3 checkmark cards) →
// H2 → CustomCTA → Signoff → Footer

window.FLOW_WELCOME_GF.e7 = {
  subject: "How the body-signal learning actually works",
  preheader: "The 'uh-oh' sensation explained, and why it bridges the gap other methods can't reach",
  day: 17,
  level: "General Family",

  // Part badge / hero
  partBadge: "Day 17 \u00b7 Mechanism",
  heroBadge: "Day 17 of your BrightKidCo journey, one more education email before the final thought.",
  h1a: "How body-signal learning",
  h1b: "actually works",
  heroSubhead: "The 'uh-oh' sensation explained, and why it bridges the gap other methods can't reach.",

  // Section 1 — Hook letter (warm cream)
  letter1First: "Whether your child is 3 or 10, verbal or non-verbal, newly diagnosed or you're still figuring it out, if they don't seem to feel when they need to go, you've probably wondered: *why?*",
  letter1Paras: [
    "And more importantly: *what actually helps?*",
    "You've seen the terms, interoception, body signals, sensory processing. Maybe you've read about the \"eighth sensory system\" from Kelly Mahler. Maybe a friend mentioned something about wetness-signal learning. Maybe you just heard a mom in a Facebook group say, \"We tried these underwear and something clicked.\"",
    "But let's be honest: all of that can feel like noise when you're on day 973 of washing pee-soaked pants.",
    "So let me explain, simply, directly, no jargon, how body-signal learning actually works. So you can decide if it's real, or if it's just another product with big claims."
  ],

  // Section 2 — FramedImage (validation hero breaker)
  validationImage: "product-photos/lifestyle/toddler-livingroom-dino-yellow.png",
  validationImageAlt: "A toddler at home in a calm living-room moment, a soft visual pause between the hook and the validation, the kind of quiet day parents actually live.",
  validationImageLabel: "VALIDATION \u00b7 THE ALMOST-TRAINED MOM",
  validationImageSublabel: "Hero break: warm living-room scene, no clinical setting, ratio ~4:3, hard shadow=6",
  validationImageShadow: 6,

  // Section 3 — Validation letter (4px Warm Amber #E8923C left-border treatment)
  letter2First: "First: you're not wrong about what's happening.",
  letter2Paras: [
    "If your child doesn't react to being wet, or reacts too late, that's not stubbornness. It's not defiance. And it's definitely not your parenting.",
    "Research shows that over 90% of autistic children have sensory processing differences (Leekam et al. 2007; Ben-Sasson et al. 2009). One of the most impactful is **interoception**, the sense that tells your body \"I need to go to the bathroom,\" \"I'm hungry,\" \"I'm thirsty.\"",
    "For many autistic children, that signal either arrives too late or doesn't arrive at all.",
    "One mom put it like this: *\"He'll start to pee and THeeeen run (while peeing).*\"",
    "Another: *\"He's been 'almost trained' for months.\"*",
    "That timing gap, the signal arriving milliseconds after the event, is the real problem. Not motivation. Not understanding. The signal itself."
  ],
  validationBorderLeft: "4px solid #E8923C",
  validationPaddingLeft: 18,

  // Section 4 — Mechanism eyebrow + H2 anchor
  mechanismEyebrow: "THE DEEP MECHANISM",
  mechanismEyebrowColor: "#E8923C",
  mechanismH2: "The Body-Signal Learning Layer, in three parts",

  // Section 5 — Mechanism lead letter (off-white #FAF7F2)
  letter3First: "Here's how body-signal learning underwear actually works, and why it's different from every other method you've tried.",
  letter3Paras: [
    "**The core insight:** Traditional potty training assumes your child can feel the \"I need to go\" signal. But for autistic children with body signal differences, that signal doesn't arrive reliably. Research shows the deficit is in **accuracy, not absence**, the signal is there, it's just not registering at the right time.",
    "This why timed methods fail. You can't build awareness with a clock when the brain isn't receiving the data."
  ],

  // Section 6 — LayerRow (3-layer mechanism explainer)
  layerRows: [
    {
      layer_number: "Layer 1",
      title: "Signal Creation",
      icon: "amber_dot",
      icon_color: "#E8923C",
      duration: "30 to 60 seconds",
      body: "A gentle, sustained \"uh-oh\" sensation that lasts 30-60 seconds. Unlike pull-ups that wick moisture away instantly, the BSL layer lets the sensation linger, long enough for the brain to register: *something happened.*",
      accent_border: "#E8923C"
    },
    {
      layer_number: "Layer 2",
      title: "Smart Absorption",
      icon: "beige_wave",
      icon_color: "#F5E6D3",
      duration: "All day",
      body: "Protects furniture and clothing without blocking the learning signal.",
      accent_border: "#D9C6A8"
    },
    {
      layer_number: "Layer 3",
      title: "Leak-Resistant Barrier",
      icon: "teal_shield",
      icon_color: "#5B9B8A",
      duration: "Contains accidents",
      body: "Contains accidents without feeling like a diaper.",
      accent_border: "#5B9B8A"
    }
  ],

  // Section 7 — Mechanism metaphor closer letter (pale teal #EAF6F2)
  letter4First: "**Think of it like training wheels for the body signal system.**",
  letter4Paras: [
    "The underwear doesn't teach your child to feel. It gives their brain the information it needs, consistently, until the neural pathways start to form on their own."
  ],

  // Section 8 — Testimonials eyebrow + TestimonialQuintet
  testimonialsEyebrow: "WHAT THAT LOOKS LIKE, REAL STORIES, REAL KIDS",
  testimonialsEyebrowColor: "#5B9B8A",
  testimonialsIntro: "Here's what that looks like in real life, across different kids, different levels, different timelines:",
  testimonials: [
    {
      label: "MINI-WIN 1",
      level_tag: "L1",
      border_color: "#E8A98F",
      indent: "left",
      quote: "He stayed dry for 2 hours. That never happened before.",
      by: "L1 parent"
    },
    {
      label: "MINI-WIN 2",
      level_tag: "L1",
      border_color: "#E8A98F",
      indent: "right",
      quote: "She told me BEFORE for the first time.",
      by: "L1 parent"
    },
    {
      label: "MINI-WIN 3",
      level_tag: "L2",
      border_color: "#8AB9B5",
      indent: "left",
      quote: "He initiated. Once. After 4 years, that was everything.",
      by: "L2 parent"
    },
    {
      label: "MINI-WIN 4",
      level_tag: "Cross",
      border_color: "#D4B886",
      indent: "right",
      quote: "He paused. He looked down. Then he walked to the potty. Small, but that never happened before.",
      by: "Cross-level testimonial"
    },
    {
      label: "MINI-WIN 5",
      level_tag: "L3",
      border_color: "#B0A0C0",
      indent: "left",
      quote: "I've made peace with maybe never. But after 8 weeks, he felt something. And that's more than we had in 9 years.",
      by: "L3 parent"
    }
  ],

  // Section 9 — Testimonials closing letter (warm cream)
  letter5First: "**Common thread across every one of these stories:** The first sign isn't \"fully trained.\" It's a *pause.* A *look.* A *step toward the bathroom.* A moment of awareness where before there was nothing.",
  letter5Paras: [
    "For some kids, that first sign comes in 2 weeks. For others, it takes 8 weeks or more. Both are normal. The research confirms interoception can be trained (Hample, Mahler & Amspacher 2020), but it happens on your child's timeline, not a calendar."
  ],

  // Section 10 — FramedImage product hero (flat-lay, shadow=4)
  productHeroImage: "product-photos/flat-lay/training-pant-cloud-raindrop-white.jpg",
  productHeroImageAlt: "Flat-lay of the white cloud-raindrop training pant, the cotton inner layer that creates the gentle uh-oh sensation.",
  productHeroImageLabel: "THE 3+3 BUNDLE",
  productHeroImageSublabel: "Body-Signal Learning Layer, cotton inner, smart absorption, leak-resistant outer. 6 pairs for a proper rotation. Ratio ~1:1, hard shadow=4",
  productHeroImageShadow: 4,

  // Section 11 — ProductShowcaseFull
  productLabel: "THE PRODUCT",
  productTitle: "3+3 Bundle.",
  productTitleAccent: "6 pairs, full rotation.",
  productSub: "Cotton inner + smart absorption. Free shipping on the bundle. 60-day guarantee.",
  productPriceFrom: "\u20ac79.99",
  productPriceNote: "3+3 Bundle \u00b7 6 pairs \u00b7 free shipping \u00b7 60-day guarantee",
  productCta: "Try the 3+3 Bundle, \u20ac79.99",
  productFeatures: [
    { icon: "\u25c9", label: "Body-Signal Learning Layer" },
    { icon: "\u2713", label: "60-day guarantee" },
    { icon: "\u2661", label: "Sensory-friendly cotton" }
  ],
  productAgeRange: "Ages 3 to 10+",
  productMicroTrust: "Free shipping on the 3+3 Bundle \u00b7 60-day guarantee \u00b7 Real returns, no forms",
  productMainImage: "product-photos/flat-lay/training-pant-fox-woodland-white.jpg",
  productSecondaryImage: "product-photos/flat-lay/training-pant-watermelon-pink.jpg",

  // Section 12 — Product bullets letter (ivory)
  letter6First: "**What you get:**",
  letter6Paras: [
    "6 pairs (3 cotton inner + 3 smart absorption layers)",
    "Free shipping (\u20ac79.99 total)",
    "60-day risk-free trial",
    "Sizes for children ages 3 to 10+",
    "**Or start with 1 pair (\u20ac34.99)**, try it alongside your current routine. No replacement. Just an addition to see if the \"uh-oh\" sensation makes a difference for your child."
  ],

  // Section 13 — GuaranteeBlock
  guaranteeLabel: "THE 60-DAY GUARANTEE",
  guaranteeHeadline: "60 days.",
  guaranteeHeadlineAccent: "By your judgment.",
  guaranteeSub: "If your child shows no sign of body awareness, no pause, no look, no step toward the potty, no change in their awareness pattern, full refund. No questions. No returns needed for the first pair.",
  guaranteeSealNumber: "60",
  guaranteeSealLabel: "Calm Days",
  guaranteeSealRing: "Calm Progress \u00b7 No Questions \u00b7 Real Returns \u00b7 Sixty Full Days",
  guaranteePoints: [
    {
      title: "Try it for 60 full days.",
      body: "Wear the Body-Signal Learning Layer on the normal routine. Watch for the small signs.",
      color: "#8AB9B5"
    },
    {
      title: "Any sign of awareness counts.",
      body: "A pause, a look, a step toward the bathroom. That's the signal working. That's enough.",
      color: "#D4B886"
    },
    {
      title: "Full refund, no questions.",
      body: "If nothing changes, email us. We refund you. No forms, no proof of progress required.",
      color: "#E8A98F"
    }
  ],
  guaranteeCloser: "The guarantee isn't a sales tactic. It's the only honest thing to offer when the outcome depends on your child's nervous system. Some kids respond in weeks. Some need longer. The 60-day window gives you enough time to know.",

  // Section 14 — CTA H2 + CustomCTA
  ctaH2: "Ready to see if the body-signal approach works for your child?",
  ctaIntro: "**Ready to see if the body-signal approach works for your child?**",
  ctaButton: "Try the 3+3 Bundle, \u20ac79.99",
  ctaButtonArrow: "\u2192",
  ctaHref: "https://www.brightkidco.com/collections/all-products",
  ctaFinePrint: "Free shipping \u00b7 60-day guarantee \u00b7 Your judgment",
  ctaSecondaryLink: "Not ready for 6 pairs? Start with 1 Pair (\u20ac34.99) \u2192",
  ctaSecondaryHref: "https://www.brightkidco.com/products/single-pair",
  ctaPriceNote: "That's \u20ac13.33 per pair with the bundle, less than half the single-pair price.",
  ctaPsLine: "Next time: One last thought before you decide.",

  // Signoff / closing (LONG variant)
  signoffName: "Lena Bauer",
  signoffClosing: "With care",
  signoffMessage: "If you have a question, about the mechanism, the timing, whether this right for your child, hit reply. You'll get me, not a bot. I have two autistic sons. One trained at 6, the other at almost 8. I've been where you are, and I know the difference between \"I'm interested\" and \"I've been burned before.\" Whatever you decide, this email won't be the last you hear from me. The product will be here next month. So will I.",

  // Footer
  footerAddress: "BrightKidCo, 123 Commerce Street, Suite 200, Nashville, TN 37201"
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 8
// ═══════════════════════════════════════════════════════════════
// welcome-01-e8-gf · content copy data
// Plain copy fields — referenced by emails.jsx via window.FLOW_WELCOME_GF.e8
//
// Final offer / soft close · Day 21 · Part 8 of 8
// BAB (Before-After-Bridge) — soft close variant
// Permission-based, inclusive, gentle off-ramp
//
// Components (per blueprint):
// EmailShell → Header → PartBadge → TitleBlock → Band (cream wash)
// Letter (hook) → FramedImage (rearview open field) → H2 (recap heading)
// RecapCard × 4 (2x2 grid: science, mechanism, signal layer, guarantee)
// FramedImage (recap inline breaker) → MigrationAnchorCard (quiz link, gold border)
// Band → H2 (offer section heading) → OfferCard (1 Pair primary) → OfferSeparator
// OfferCard (3+3 Bundle secondary) → FramedImage (product flat-lay)
// Band (cream → teal) → H2 (guarantee heading) → GuaranteeBlock (60-day seal + 3 points)
// Band (teal → cream) → FramedImage (washing machine soft-close breaker)
// Signoff (Lena Bauer, long variant) → Footer

window.FLOW_WELCOME_GF.e8 = {
  subject: "One last thing before you decide",
  preheader: "Whether your child shows no signs at all or just needs a little extra time, we made this easy.",
  day: 21,
  level: "General Family",

  // Part badge / hero
  partBadge: "Part 8 of 8 \u00b7 Day 21 \u00b7 Final",
  heroBadge: "Part 8 of 8 \u00b7 Day 21",
  h1a: "One last thing",
  h1b: "before you decide",
  heroSubhead: "Three weeks of information, then a quiet choice. No pressure either way.",

  // Section 1 — Hook letter (warm cream) — §HOOK verbatim
  letterHookFirst: "You've been reading these emails for three weeks. Maybe you've bookmarked a page. Maybe you've talked to your partner. Maybe you've watched your child and thought, \"I'm still not sure.\"",
  letterHookParas: [
    "That's exactly where you're supposed to be."
  ],

  // Section 2 — Recap lead visual (rearview open field)
  recapLeadImage: "product-photos/lifestyle/toddler-rearview-cat-mustard.png",
  recapLeadAlt: "A toddler seen from behind in a calm domestic moment, the wide clearing at dusk, the visual metaphor for the open field invitation",
  recapLeadLabel: "THE OPEN FIELD \u00b7 WIDE LANDSCAPE",
  recapLeadSublabel: "Hero image. Warm dusk palette, no urgency, no arrows. A child at a clearing. Ratio ~4:3",
  recapLeadShadow: 6,

  // Section 3 — Recap section H2
  h2Recap: "21 days, four big ideas",

  // Section 4 — RecapCard × 4 (2x2 grid)
  // warm stone bg #F0EAE1, 2px ink border, hard shadow=4, 14px border-radius
  recapCards: [
    {
      label: "01 \u00b7 THE SCIENCE",
      icon: "\ud83d\udd2c",
      title: "Why some children don't feel the signal",
      body: "It's not training. It's neurology. Research shows many children with sensory differences have diminished body awareness. The \"I need to go\" signal doesn't arrive in time, or at all."
    },
    {
      label: "02 \u00b7 THE PULL-UP PROBLEM",
      icon: "\ud83e\udde0",
      title: "Why pull-ups block the one thing your child needs",
      body: "They wick away the very sensation that teaches the brain. The body-signal layer needs feedback to learn."
    },
    {
      label: "03 \u00b7 THE MECHANISM",
      icon: "\ud83d\udca7",
      title: "How the Body-Signal Learning Layer works",
      body: "A gentle sensation that lasts that gives the nervous system 30-60 seconds to register: something happened. That's the window most children never get."
    },
    {
      label: "04 \u00b7 THE GUARANTEE",
      icon: "\u2705",
      title: "The 60-day guarantee",
      body: "Try it. By your judgment. If it doesn't work for your child, full refund. No questions. No pressure."
    }
  ],

  // Section 5 — Recap inline breaker (visual breath before migration anchor)
  recapBreakerImage: "product-photos/lifestyle/toddler-outdoors-grass-disposable-diaper.png",
  recapBreakerAlt: "A toddler outside on the grass, the kinds of families the recap content speaks to",
  recapBreakerLabel: "MID-BODY \u00b7 THE RECAP LANDS",
  recapBreakerSublabel: "Inline breaker between the 4-card recap grid and the migration anchor. Ratio ~4:3",
  recapBreakerShadow: 3,

  // Section 6 — Recap closing paragraph (§RECAP closing)
  recapClosing: "If any of this sounds familiar, if your child doesn't seem to feel when they need to go, if pull-ups are the only thing that works but you know they're not teaching, if you've tried methods that assume a signal that just isn't there, then you know exactly why this approach is different.",

  // Section 7 — MigrationAnchorCard (3px gold border, quiz link, constellation easter egg)
  migrationEyebrow: "MORE DETAILED ASSESSMENT",
  migrationEyebrowColor: "#D4A76A",
  migrationHeadline: "If your child sounds like any of these descriptions, click here for a more detailed assessment.",
  migrationHeadlineAccent: "more detailed assessment",
  migrationBodyLead: "This short quiz helps us match your child's specific needs to the right approach, whether they're just starting to show signs or you've been at this for years. It takes two minutes.",
  migrationCtaLabel: "More Detailed Assessment",
  migrationCtaArrow: "\u2192",
  migrationCtaHref: "https://www.brightkidco.com/pages/assessment",

  // Section 8 — Offer section H2
  h2Offer: "This the only offer we make",

  // Section 9 — OfferCard primary (1 Pair)
  offerPrimaryEyebrow: "START SMALL",
  offerPrimaryLabel: "1 PAIR",
  offerPrimaryPrice: "\u20ac34.99",
  offerPrimaryLineOne: "60-Day Guarantee, No Pressure.",
  offerPrimaryLineTwo: "Start with a single pair. Add it alongside whatever you're currently doing. Pull-ups, underwear, bare-bottom, it doesn't matter. Just one pair that gives his nervous system the signal it's been missing.",
  offerPrimaryCtaLabel: "Start With 1 Pair, \u20ac34.99",
  offerPrimaryCtaArrow: "\u2192",
  offerPrimaryCtaHref: "https://www.brightkidco.com/products/body-signal-learning-underwear",
  offerPrimaryWhisper: "No pressure",

  // Section 10 — OfferSeparator (soft gold hr with "or")
  offerSeparatorText: "or",

  // Section 11 — OfferCard secondary (3+3 Bundle)
  offerSecondaryEyebrow: "THE FULL APPROACH",
  offerSecondaryLabel: "3+3 BUNDLE",
  offerSecondaryPrice: "\u20ac79.99",
  offerSecondaryLineOne: "Free Shipping.",
  offerSecondaryRationaleHeading: "Why 3+3?",
  offerSecondaryRationaleBody: "Six pairs means you're never washing mid-week. Three days of wear, three in the laundry. At \u20ac79.99 with free shipping, that's \u20ac13.33 per pair, and they last through multiple children.",
  offerSecondaryComparisonLine: "That's \u20ac13.33 per pair with the bundle. Less than half the single-pair price.",
  offerSecondaryCtaLabel: "3+3 Bundle, \u20ac79.99",
  offerSecondaryCtaArrow: "\u2192",
  offerSecondaryCtaHref: "https://www.brightkidco.com/products/3-3-bundle",

  // Section 12 — Offer inline product visual
  offerProductImage: "product-photos/flat-lay/training-pant-watermelon-pink.jpg",
  offerProductAlt: "The body-signal learning pant flat lay, the product in 1 Pair and 3+3 Bundle offer",
  offerProductLabel: "PRODUCT \u00b7 THE 1 PAIR & 3+3 BUNDLE",
  offerProductSublabel: "Inline product visual. The body-signal learning pant that makes both offers concrete. Ratio ~4:3",
  offerProductShadow: 3,

  // Section 13 — Guarantee section H2
  h2Guarantee: "60 days. By your judgment.",

  // Section 14 — GuaranteeBlock (60-day circular seal + 3 checkmark cards)
  guaranteeLabel: "60-DAY GUARANTEE",
  guaranteeHeadline: "60 days. Your judgment.",
  guaranteeHeadlineAccent: "60 days",
  guaranteeSub: "Try it. By your judgment. If it doesn't work for your child, full refund. No questions. No pressure. The guarantee isn't a sales tactic. It's the only honest thing to offer when the outcome depends on your child's nervous system.",
  guaranteeSealNumber: "60",
  guaranteeSealLabel: "Calm Days",
  guaranteeSealRing: "Calm Progress \u00b7 No Questions \u00b7 Real Returns \u00b7 Sixty Full Days",
  guaranteePoints: [
    {
      title: "Try it for 60 full days.",
      body: "Wear the Body-Signal Learning Layer on the normal routine. Watch for the small signs.",
      color: "#8AB9B5"
    },
    {
      title: "Any sign of awareness counts.",
      body: "A pause, a look, a step toward the bathroom. That's the signal working. That's enough.",
      color: "#D4B886"
    },
    {
      title: "Full refund, no questions.",
      body: "If nothing changes, email us. We refund you. No forms, no proof of progress required.",
      color: "#E8A98F"
    }
  ],

  // Section 15 — Soft close inline breaker (washing machine, real-life detail)
  softCloseImage: "product-photos/lifestyle/washing-machine-training-pants.png",
  softCloseAlt: "A washing machine with training pants, the practical visual that pairs with the 3+3 Bundle offer",
  softCloseLabel: "SOFT CLOSE \u00b7 THE PRACTICAL DETAIL",
  softCloseSublabel: "Inline breaker before Lena sign-off. The real-life detail of the bundle offer. Ratio ~4:3",
  softCloseShadow: 3,

  // Section 16 — Signoff (Lena Bauer, long variant per Layer-09-voice-lena.md §8.4)
  signoffName: "Lena Bauer",
  signoffClosing: "With care",
  psLine: "P.S. My older son was 8 before we figured this out. If you've stepped back from trying, I get it. 60 days, your judgment. No pressure.",

  // Footer
  footerAddress: "BrightKidCo, 123 Commerce Street, Suite 200, Portland, OR 97201, United States",
  footerTagline: "Reply to this email, Lena reads every response personally."
};


// Shared signoff / footer / out for the whole flow (consumed by Signoff, Footer, OutLine primitives)
window.FLOW_WELCOME_GF_SHARED = {
  signoff: {
    line1: "With you,",
    name: "Lena Bauer",
    ps: "P.S. If you ever want to reply and tell me about your child, I read every one. Really.",
  },
  out: "You can pause this series anytime. Come back when you're ready.",
  footer: {
    tagline: "Calm progress, one day at a time.",
    links: ["Our Method", "Shop the Pants", "Parent Stories"],
    address: "BrightKidCo Ltd · Berlin, Germany · hello@brightkidco.com",
  },
};
window.FLOW1_SHARED = window.FLOW_WELCOME_GF_SHARED;
