/* Welcome GF · 8 Email Components · Generated by sub-agents per blueprint + plan
   Uses shared primitives from welcome-flow/primitives.jsx
   No imports. Primitives come from window.* (set by the Local.html loader).
*/

const {
  EmailShell, Header, PartBadge, TitleBlock, Eyebrow, H2, Letter, Band,
  FramedImage, ImgFrame, CTAClose, Signoff, OutLine, Footer,
  ProductShowcaseFull, ProductShowcaseMedium, ProductShowcaseSoft
} = window;
const B = window.BRAND;
const F = window.FONT;

// HeroImage helper: framed image with src, alt, label, shadow. Used by emails that
// reference lifestyle/flat-lay photos in the hero slot.
const HeroImage = ({ src, alt, label, sublabel, height = 240, shadow = 6 }) => (
  <div style={{ margin: "24px 14px 0" }}>
    <FramedImage height={height} shadow={shadow}>
      {src ? (
        <img src={src} alt={alt || label || "Hero image"} style={{ width: "100%", height, objectFit: "cover", display: "block" }} />
      ) : (
        <ImgFrame height={height} label={label} sublabel={sublabel} />
      )}
    </FramedImage>
  </div>
);

// ═══════════════════════════════════════════════════════════════
// EMAIL 1
// ═══════════════════════════════════════════════════════════════
const Email1 = () => {
  const c = window.FLOW_WELCOME_GF.e1;

  return (
    <EmailShell preheader={c.preheader} bg="#FFFBF0">
      <Header bg="#FFFBF0" />

      {/* Hero . toddler image */}
      <HeroImage
        height={240}
        label="HERO · TODDLER IN LIVING ROOM"
        sublabel="A toddler in a warm living room, looking at the camera. Ratio ~5:3"
        shadow={6}
        src={c.heroImage}
        alt={c.heroAlt}
      />

      <TitleBlock
        badge={c.heroBadge}
        part1={c.h1a}
        part2={c.h1b}
        subhead={c.heroSubhead}
      />

      {/* Section 1 . Opening letter: what you've tried, why nothing worked */}
      <Letter bg="#FFF6E2" first={c.letter1First} paras={c.letter1Paras} />

      {/* Section 2 . The mechanism H2 + body letter */}
      <H2 children={c.h2Mechanism} center size={22} />
      <Letter bg="#EAF6F2" first={c.letter2First} paras={c.letter2Paras} />

      {/* Mechanism image . training pant flat lay */}
      <div style={{ background: "#EAF6F2", padding: "4px 14px 24px" }}>
        <HeroImage
          height={200}
          label="PRODUCT · TRAINING PANT FLAT LAY"
          sublabel="The Body-Signal Learning System that creates the wetness signal pull-ups block. Ratio ~4:3"
          shadow={4}
          src={c.mechanismImage}
          alt={c.mechanismAlt}
        />
      </div>

      {/* Section 3 . Letter about the product approach */}
      <Letter bg="#FFFBF0" first={c.letter3First} paras={c.letter3Paras} />

      {/* Section 4 . Product showcase medium */}
      <div style={{ background: "#FFFBF0" }}>
        <ProductShowcaseMedium
          product={c.productName}
          image_src={c.productImage}
          price_label={c.productPrice}
        />
      </div>

      {/* Section 5 . Testimonials / what other parents found */}
      <Letter bg="#FFFBF0" first={c.letter4First} paras={c.letter4Paras} />

      {/* Section 6 . Try it for 60 days */}
      <H2 children={c.h2Try} center size={22} />
      <Letter bg="#FFF6E2" first={c.letter5First} paras={c.letter5Paras} />

      {/* Section 7 . Keep reading + CTA inline */}
      <H2 children={c.h2KeepReading} center size={20} />
      <Letter bg="#FFFBF0" first={c.letter6First} paras={c.letter6Paras} />

      {/* Inline CTA . B.ink bg, lime green button, real href from content */}
      <div style={{ background: B.ink, padding: "20px 22px 44px", textAlign: "center", color: "#FFF" }}>
        <p style={{ fontSize: 14, lineHeight: 1.6, color: "#B8CACD", margin: "0 0 24px" }}>{c.ctaIntro}</p>
        <a href="#" style={{
          display: "inline-block", padding: "17px 32px",
          background: "#D8F57C", color: B.ink, fontSize: 15.5, fontWeight: 700,
          textDecoration: "none", borderRadius: 999, letterSpacing: 0.3,
        }}>{c.ctaButton} →</a>
        <div style={{ marginTop: 16, fontSize: 11.5, color: "#8A9B9D" }}>{c.ctaFinePrint}</div>
      </div>

      <Signoff />
      <OutLine />
      <Footer />
    </EmailShell>
  );
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 2
// ═══════════════════════════════════════════════════════════════
const Email2 = () => {
  const c = window.FLOW_WELCOME_GF.e2;
  const BG_HERO = "#FFFBF0";
  const BG_LETTER = "#FFF6E2";
  const BG_MECHANISM = "#EAF6F2";
  const BG_FAILED = "#EAF6F2";
  const BG_CTA = "#1F2D2F";

  return (
    <EmailShell preheader={c.preheader} bg={BG_HERO}>
      <Header bg={BG_HERO} />

      {/* Standalone PartBadge (e2 introduces this BEFORE the title, per e1/e2/e5 pattern) */}
      <div style={{ background: BG_HERO, padding: "24px 22px 0", textAlign: "center" }}>
        <PartBadge>{c.partBadge}</PartBadge>
      </div>

      <TitleBlock
        badge={c.heroBadge}
        part1={c.h1a}
        part2={c.h1b}
        subhead={c.heroSubhead}
      />

      {/* Hero . circular teal frame, hard shadow 6 */}
      <div style={{ margin: "24px 14px 0" }}>
        <FramedImage
          height={240}
          label={c.heroLabel}
          sublabel={c.heroSublabel}
          shadow={c.heroShadow}
        />
      </div>

      <Band from={BG_HERO} to={BG_LETTER} />

      {/* Letter with 4px emerald left border (Failed Methods Recognition paragraph treatment) */}
      <div style={{ background: BG_LETTER, borderLeft: "4px solid #039902", paddingLeft: 18 }}>
        <Letter
          bg={BG_LETTER}
          first={c.letter1First}
          paras={c.letter1Paras}
        />
      </div>

      <Band from={BG_LETTER} to={BG_MECHANISM} height={40} />

      {/* MechanismDef . eyebrow + gradient H2 + body lead + 2 body paras + 49% stat callout */}
      <div style={{ background: BG_MECHANISM, padding: "32px 22px 20px" }}>
        <div style={{ fontSize: 10.5, letterSpacing: 3, textTransform: "uppercase", color: "#039902", fontWeight: 700, marginBottom: 10 }}>
          {c.mechanismEyebrow}
        </div>
        <h2 style={{ fontSize: 32, lineHeight: 1.1, fontWeight: 700, margin: "0 0 18px", letterSpacing: -0.5, textAlign: "left" }}>
          <span style={{
            background: "linear-gradient(135deg, #039902 0%, #5BC0BE 100%)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            backgroundClip: "text",
            color: "transparent",
            fontWeight: 700,
          }}>{c.mechanismTitleAccent}</span>.
        </h2>
        <p style={{ margin: "0 0 14px", fontSize: 17, color: B.ink, fontWeight: 600, lineHeight: 1.55 }}>
          {c.mechanismBodyLead}
        </p>
        {c.mechanismBodyParas.map((p, i) => (
          <p key={i} style={{ margin: "0 0 14px", fontSize: 15, lineHeight: 1.7, color: B.soft }}>
            {p}
          </p>
        ))}
      </div>

      {/* 49% stat callout . white card with hard shadow, on teal background */}
      <div style={{ background: BG_MECHANISM, padding: "4px 22px 28px" }}>
        <div style={{
          background: "#FFFFFF",
          border: `2px solid ${B.ink}`,
          borderRadius: 18,
          boxShadow: `4px 4px 0 ${B.ink}`,
          padding: "22px 20px 20px",
        }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginBottom: 8 }}>
            <div style={{
              fontSize: 56, lineHeight: 1, fontWeight: 700,
              ...B.gradientText,
            }}>{c.mechanismStatNumber}</div>
            <div style={{ fontSize: 13, color: B.ink, fontWeight: 600, lineHeight: 1.3, flex: 1 }}>
              {c.mechanismStatLabel}
            </div>
          </div>
          <p style={{ margin: "0 0 10px", fontSize: 13.5, lineHeight: 1.6, color: B.soft }}>
            {c.mechanismStatCompare}
          </p>
          <div style={{ fontSize: 11, letterSpacing: 1.2, textTransform: "uppercase", color: B.muted, fontWeight: 700 }}>
            {c.mechanismStatCitation}
          </div>
        </div>
      </div>

      {/* Mid-body inline breaker . hard shadow 3 */}
      <div style={{ background: BG_MECHANISM, padding: "4px 14px 24px" }}>
        <FramedImage
          height={200}
          label={c.inlineLabel2}
          sublabel={c.inlineSublabel2}
          shadow={c.inlineShadow2}
        />
      </div>

      <Band from={BG_MECHANISM} to={BG_FAILED} height={0} />

      {/* FailedMethodsGrid . 4 cards in 2x2 vertical stack: 3 X (Coral) + 1 check (Brand Green) */}
      <div style={{ background: BG_FAILED, padding: "32px 18px 16px" }}>
        <div style={{ padding: "0 4px 20px", textAlign: "center" }}>
          <div style={{ fontSize: 10.5, letterSpacing: 2, textTransform: "uppercase", color: B.tealDeep, fontWeight: 700, marginBottom: 10 }}>
            {c.failedIntroEyebrow}
          </div>
          <h2 style={{ fontSize: 26, lineHeight: 1.15, fontWeight: 700, margin: "0 0 14px", letterSpacing: -0.4, textAlign: "center" }}>
            {c.failedIntroTitle}
          </h2>
          <p style={{ fontSize: 15, lineHeight: 1.65, color: B.soft, margin: 0, textAlign: "left" }}>
            {c.failedIntroBody}
          </p>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {c.failedCards.map((card, i) => {
            const isPositive = card.icon === "✓";
            return (
              <div key={i} style={{
                background: "#FFFFFF",
                border: `2px solid ${B.ink}`,
                borderRadius: 16,
                boxShadow: `3px 3px 0 ${B.ink}`,
                padding: "18px 20px",
                display: "flex",
                gap: 14,
                alignItems: "flex-start",
              }}>
                {/* icon block */}
                <div style={{
                  flexShrink: 0,
                  width: 40, height: 40,
                  borderRadius: 10,
                  background: card.iconColor,
                  color: "#FFFFFF",
                  fontSize: 20, fontWeight: 700,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  border: `2px solid ${B.ink}`,
                }}>{card.icon}</div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{
                    fontSize: 10.5, letterSpacing: 1.5, textTransform: "uppercase",
                    color: card.iconColor, fontWeight: 700, marginBottom: 4,
                  }}>{card.label}</div>
                  <div style={{ fontSize: 15.5, fontWeight: 700, color: B.ink, lineHeight: 1.3, marginBottom: 6 }}>
                    {card.header}
                  </div>
                  <p style={{ margin: 0, fontSize: 13.5, lineHeight: 1.55, color: B.soft }}>
                    {card.body}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Guide breaker . hard shadow 3 */}
      <div style={{ background: BG_FAILED, padding: "16px 14px 28px" }}>
        <FramedImage
          height={200}
          label={c.inlineLabel3}
          sublabel={c.inlineSublabel3}
          shadow={c.inlineShadow3}
        />
      </div>

      <Band from={BG_FAILED} to={BG_CTA} height={50} />

      {/* Inline CTA . NOT CTAClose primitive, per task spec */}
      <div style={{ background: BG_CTA, padding: "32px 22px 44px", textAlign: "center", color: "#FFFFFF" }}>
        <p style={{ fontSize: 15, lineHeight: 1.65, color: "#B8CACD", margin: "0 0 18px" }}>
          {c.ctaIntro}
        </p>
        <p style={{ fontSize: 14, lineHeight: 1.6, color: "#B8CACD", margin: "0 0 26px", fontStyle: "italic" }}>
          {c.ctaIntroSecondary}
        </p>
        <a href={c.ctaHref} style={{
          display: "inline-block", padding: "17px 32px",
          background: "#D8F57C", color: B.ink, fontSize: 15.5, fontWeight: 700,
          textDecoration: "none", borderRadius: 999, letterSpacing: 0.3,
        }}>{c.ctaButton} →</a>
        <div style={{ marginTop: 18, fontSize: 11.5, color: "#8A9B9D" }}>
          {c.ctaFinePrint}
        </div>
        <div style={{ marginTop: 22, fontSize: 12, color: "#8FAFB2", fontStyle: "italic" }}>
          {c.ctaNextTime}
        </div>
      </div>

      <Signoff />
      <Footer />
    </EmailShell>
  );
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 3
// ═══════════════════════════════════════════════════════════════
const Email3 = () => {
  const c = window.FLOW_WELCOME_GF.e3;
  const BG_HERO = "#FFFBF0";
  const BG_LETTER_MECH = "#FFF6E2";
  const BG_LETTER_GUAR = "#EAF6F2";
  const BG_CTA = B.ink;

  // 3 family-quote card accent washes (left-border accent)
  const FAMILY_WASHES = ["#F5F0EB", "#EEF3ED", "#F0EEF5"];
  const FAMILY_SHADOWS = [6, 4, 3];

  return (
    <EmailShell preheader={c.preheader} bg={BG_HERO}>
      <Header bg={BG_HERO} />

      {/* ═══ Hero · PartBadge (49% tilted sticker) + TitleBlock ═══ */}
      <div style={{ position: "relative", padding: "26px 22px 0", textAlign: "center" }}>
        {/* Yellow tilted pill sticker (49%) — sits over the hero, rotated -1.5deg */}
        <div style={{ position: "absolute", top: 18, right: 24, zIndex: 2 }}>
          <PartBadge>{c.partBadge}</PartBadge>
        </div>
        <div style={{ position: "absolute", top: 18, left: 24, zIndex: 2 }}>
          <PartBadge>{c.heroBadge}</PartBadge>
        </div>

        <h1 style={{ fontSize: 40, lineHeight: 1, fontWeight: 700, margin: "44px 0 0", letterSpacing: -0.8 }}>
          {c.h1a}<br/>
          <span style={{ ...B.gradientText, fontWeight: 700 }}>{c.h1b}</span>
        </h1>
        {c.heroSubhead && (
          <p style={{ fontSize: 17, color: B.soft, marginTop: 14, lineHeight: 1.4, fontWeight: 500 }}>
            {c.heroSubhead}
          </p>
        )}
      </div>

      <Band from={BG_HERO} to={BG_HERO} height={24} />

      {/* ═══ Three-Family Triptych (3 FramedImage cards) ═══ */}
      {c.socialProof.map((sp, i) => (
        <div key={i} style={{ margin: i === 0 ? "0 14px 14px" : "0 14px 14px" }}>
          <div style={{
            background: FAMILY_WASHES[i],
            borderLeft: `4px solid ${B.ink}`,
            borderRadius: 18,
            padding: "16px 18px",
          }}>
            <div style={{
              fontSize: 10.5, letterSpacing: 1.6, textTransform: "uppercase",
              color: B.tealDeep, fontWeight: 700, marginBottom: 8,
            }}>
              Family {String(i + 1).padStart(2, "0")}
            </div>
            <FramedImage
              shadow={FAMILY_SHADOWS[i]}
              src={i === 0 ? c.family1Image : i === 1 ? c.family2Image : c.family3Image}
              label={`FAMILY ${String(i + 1).padStart(2, "0")} \u00b7 QUOTE CARD`}
              sublabel={sp.alt}
            />
          </div>
        </div>
      ))}

      {/* ═══ Stat Callout Box (49% breakout · ImgFrame placeholder, hard shadow=6) ═══ */}
      <div style={{ margin: "6px 14px 18px" }}>
        <FramedImage shadow={c.stat.shadow}>
          <ImgFrame
            height={220}
            label={c.stat.label}
            sublabel={c.stat.sublabel}
          />
        </FramedImage>
      </div>

      <Band from={BG_HERO} to={BG_LETTER_MECH} />

      {/* ═══ Letter · Validation + Mechanism + 3-Layer Explainer ═══
          10 paragraphs. The 3-Layer explainer is rendered as a numbered list INSIDE this
          Letter block (paras 6-9 of the blueprint), with a section header (para 5).  */}
      <div style={{ background: BG_LETTER_MECH, padding: "24px 24px 28px", fontSize: 15, lineHeight: 1.7, color: B.soft }}>
        <p style={{ margin: "0 0 14px", fontSize: 17, color: B.ink, fontWeight: 600 }}>
          {c.letter1First}
        </p>

        {/* paras 1-4: validation + mechanism context */}
        {c.letter1Paras.slice(0, 4).map((p, i) => (
          <p key={`m${i}`} style={{ margin: "0 0 14px" }}>{p}</p>
        ))}

        {/* 3-Layer explainer header */}
        <p style={{ margin: "20px 0 12px", fontSize: 16, color: B.ink, fontWeight: 700 }}>
          The 3-Layer System
        </p>

        {/* 3-layer cards (numbered list) */}
        {c.threeLayer.map((layer, i) => {
          const accents = [B.teal, B.green, "#E8A23D"];
          return (
            <div key={`l${i}`} style={{
              marginBottom: 10, background: "#FFFFFF",
              border: `2px solid ${B.ink}`, borderRadius: 14,
              padding: "12px 14px", display: "flex", gap: 12, alignItems: "flex-start",
              boxShadow: `3px 3px 0 ${B.ink}`,
            }}>
              <div style={{
                flexShrink: 0, width: 30, height: 30, borderRadius: "50%",
                background: accents[i], color: "#FFFFFF",
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: 14, fontWeight: 700, border: `2px solid ${B.ink}`,
              }}>{layer.n}</div>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 13.5, fontWeight: 700, color: B.ink, marginBottom: 4, lineHeight: 1.3 }}>
                  {layer.name}
                </div>
                <p style={{ margin: 0, fontSize: 13, lineHeight: 1.55, color: B.soft }}>
                  {layer.body}
                </p>
              </div>
            </div>
          );
        })}

        {/* closing para (thisn't a pull-up replacement...) */}
        <p style={{ margin: "16px 0 0" }}>{c.letter1Paras[9]}</p>
      </div>

      <Band from={BG_LETTER_MECH} to={BG_LETTER_GUAR} />

      {/* ═══ Letter · Testimonials + Product + Guarantee + CTA + PS ═══
          Letter bg #EAF6F2. Testimonials (paras 0-3: quote + by), product mention (para 4),
          Guarantee (paras 5-6: "60 days." + body), CTA offer (para 7: bundle label), bundle body
          (paras 8-9), secondary 1-pair (paras 10-11), closing ps (para 12).
          Inline patterns: italic quote cards with left-border accent, 60-day circular seal SVG,
          3-dot color-coded checkmark cards, inline CTA button (dark ink bg, lime #D8F57C text,
          17px 32px padding, pill radius).  */}
      <div style={{ background: BG_LETTER_GUAR, padding: "26px 22px 32px", fontSize: 15, lineHeight: 1.7, color: B.soft }}>
        {/* ── Testimonials (italic quote cards w/ left-border accent) ── */}
        {[
          { quote: c.letter2First, by: c.letter2Paras[0], wash: FAMILY_WASHES[0] },
          { quote: c.letter2Paras[1], by: c.letter2Paras[2], wash: FAMILY_WASHES[1] },
          { quote: c.letter2Paras[3], by: c.letter2Paras[4], wash: FAMILY_WASHES[2] },
        ].map((t, i) => (
          <div key={`q${i}`} style={{
            marginBottom: 14, padding: "14px 16px",
            background: "#FFFFFF",
            borderLeft: `4px solid ${t.wash}`,
            border: `2px solid ${B.ink}`,
            borderLeftWidth: 6,
            borderRadius: 14,
            boxShadow: `3px 3px 0 ${B.ink}`,
          }}>
            <p style={{
              margin: "0 0 8px", fontSize: 14.5, lineHeight: 1.55, color: B.ink,
              fontStyle: "italic", fontFamily: F.display, fontWeight: 500,
            }}>
              {t.quote}
            </p>
            <div style={{ fontSize: 11.5, color: B.muted, fontWeight: 700, letterSpacing: 0.3 }}>
              {t.by}
            </div>
          </div>
        ))}

        {/* ── Product mention ── */}
        <p style={{ margin: "16px 0 14px", fontSize: 15.5, lineHeight: 1.65, color: B.ink, fontWeight: 600 }}>
          {c.letter2Paras[5]}
        </p>

        {/* ── Guarantee header + sub ── */}
        <div style={{ textAlign: "center", margin: "6px 0 14px" }}>
          <Eyebrow color={B.tealDeep}>Our promise</Eyebrow>
          <h2 style={{ fontSize: 26, lineHeight: 1.2, fontWeight: 700, margin: "6px 0 6px", letterSpacing: -0.4 }}>
            60 days. <span style={{ ...B.gradientText, fontWeight: 700 }}>By your judgment.</span>
          </h2>
          <p style={{ fontSize: 14, color: B.soft, margin: 0, fontStyle: "italic", lineHeight: 1.5 }}>
            {c.guaranteeSub}
          </p>
        </div>

        {/* ── Inline 60-Day circular seal (SVG) ── */}
        <div style={{ display: "flex", justifyContent: "center", margin: "8px 0 14px" }}>
          <div style={{
            position: "relative", width: 200, height: 200,
            display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
            background: "#FFFFFF", borderRadius: "50%",
            border: `3px solid ${B.ink}`, boxShadow: `6px 6px 0 ${B.ink}`,
          }}>
            <svg width="200" height="200" viewBox="0 0 200 200" style={{ position: "absolute", inset: 0 }}>
              <defs>
                <path id="e3circlePath" d="M 100, 100 m -80, 0 a 80,80 0 1,1 160,0 a 80,80 0 1,1 -160,0" />
              </defs>
              <text fill={B.tealDeep} style={{ fontFamily: F.main, fontSize: 10, fontWeight: 700, letterSpacing: 3, textTransform: "uppercase" }}>
                <textPath href="#e3circlePath" startOffset="0">
                  \u00b7 Calm Progress \u00b7 No Forms \u00b7 Real Returns \u00b7 Sixty Full Days \u00b7
                </textPath>
              </text>
            </svg>
            <div style={{ fontSize: 11, letterSpacing: 2, textTransform: "uppercase", color: B.muted, fontWeight: 700, marginBottom: 4 }}>Protected by</div>
            <div style={{ fontSize: 56, fontWeight: 700, lineHeight: 1, ...B.gradientText }}>60</div>
            <div style={{ fontSize: 13, fontWeight: 700, color: B.ink, letterSpacing: 0.5, marginTop: 2 }}>Calm Days</div>
            <div style={{ fontSize: 10.5, color: B.soft, marginTop: 4, letterSpacing: 0.5 }}>Full refund \u00b7 No forms</div>
          </div>
        </div>

        {/* ── 3-dot color-coded guarantee checkmark cards ── */}
        {c.guaranteePoints.map((p, i) => {
          const accents = [B.teal, B.green, "#E8A23D"];
          return (
            <div key={`gp${i}`} style={{
              marginBottom: 10, background: "#FFFFFF", borderRadius: 14,
              overflow: "hidden", border: `2px solid ${B.ink}`,
              boxShadow: `3px 3px 0 ${B.ink}`,
              display: "flex", alignItems: "stretch",
            }}>
              <div style={{
                width: 38, flexShrink: 0, background: accents[i],
                color: "#FFFFFF", fontSize: 15, fontWeight: 700,
                display: "flex", alignItems: "center", justifyContent: "center",
                borderRight: `2px solid ${B.ink}`,
              }}>\u2713</div>
              <div style={{ padding: "12px 16px" }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: B.ink, marginBottom: 4, lineHeight: 1.3 }}>
                  {p.title}
                </div>
                <p style={{ margin: 0, fontSize: 13, lineHeight: 1.5, color: B.soft }}>{p.body}</p>
              </div>
            </div>
          );
        })}

        {/* ── CTA section: bundle offer body + inline CTA button ── */}
        <div style={{ margin: "22px 0 12px", padding: "16px 16px 18px", background: "#FFFFFF", border: `2px solid ${B.ink}`, borderRadius: 16, boxShadow: `4px 4px 0 ${B.ink}` }}>
          <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: 12, marginBottom: 8 }}>
            <div style={{ fontSize: 17, fontWeight: 700, color: B.ink }}>{c.offer.primary.label}</div>
            <div style={{ fontSize: 22, fontWeight: 700, color: B.ink, ...B.gradientText }}>{c.offer.primary.price}</div>
          </div>
          <p style={{ margin: "0 0 14px", fontSize: 13, lineHeight: 1.55, color: B.soft }}>
            {c.offer.primary.note}
          </p>
          <p style={{ margin: "0 0 14px", fontSize: 13.5, lineHeight: 1.6, color: B.ink }}>
            {c.letter2Paras[9]}
          </p>
          {/* Inline CTA button (dark ink bg, lime #D8F57C button text, 17px 32px padding, pill radius) */}
          <div style={{ textAlign: "center", marginTop: 6 }}>
            <a href={c.offer.primary.href} style={{
              display: "inline-block", padding: "17px 32px",
              background: B.ink, color: "#D8F57C", fontSize: 15.5, fontWeight: 700,
              textDecoration: "none", borderRadius: 999, letterSpacing: 0.3,
            }}>{c.ctaButton} \u2192</a>
          </div>
          <p style={{ margin: "14px 0 0", fontSize: 12.5, lineHeight: 1.55, color: B.soft, fontStyle: "italic", textAlign: "center" }}>
            {c.letter2Paras[10]}
          </p>
          <p style={{ margin: "6px 0 0", fontSize: 12.5, lineHeight: 1.55, color: B.muted, textAlign: "center" }}>
            {c.letter2Paras[11]}
          </p>
        </div>

        {/* PS line */}
        <p style={{ margin: "18px 0 0", fontSize: 13, color: B.soft, fontStyle: "italic" }}>
          <span style={{ color: B.tealDeep, fontWeight: 700, fontStyle: "normal", marginRight: 4 }}>Next time:</span>
          {c.letter2Paras[12].replace(/^Next time:\s*/i, "")}
        </p>
      </div>

      <Band from={BG_LETTER_GUAR} to={BG_CTA} height={50} />

      {/* ═══ Signoff (reads from window.FLOW_WELCOME_GF_SHARED.signoff) ═══ */}
      <Signoff />
      <OutLine />
      <Footer />
    </EmailShell>
  );
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 4
// ═══════════════════════════════════════════════════════════════
const Email4 = () => {
  const c = window.FLOW_WELCOME_GF.e4;
  const B = window.BRAND;
  const F = window.FONT;

  const BG_HERO = "#FFFBF0";
  const BG_CREAM = "#FFF6E2";
  const BG_MINT = "#EAF6F2";
  const BG_LAVENDER = "#F0EDF8";
  const BG_GUARANTEE = "#FFFBF0";
  const BG_CTA = "#1F2D2F";

  return (
    <EmailShell preheader={c.preheader} bg={BG_HERO}>
      <Header bg={BG_HERO} />

      {/* 1. EmailShell (above) — 2. Header (above) */}

      {/* 3. Hero — framed lifestyle image */}
      <div style={{ margin: "24px 14px 0" }}>
        <FramedImage
          height={260}
          label={c.heroAlt}
          sublabel="Candid warm lifestyle moment of a child at play, no clinical setting, no bathroom in frame. Ratio ~5:3"
          shadow={6}
        >
          <img
            src={c.heroImage}
            alt={c.heroAlt}
            style={{ width: "100%", height: 260, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 4. Title block */}
      <TitleBlock
        badge={c.heroBadge}
        part1={c.h1a}
        part2={c.h1b}
        subhead={c.subhead}
      />

      {/* 5. Band: cream → cream-yellow */}
      <Band from={BG_HERO} to={BG_CREAM} height={40} />

      {/* 6. Opening letter */}
      <Letter bg={BG_CREAM} first={c.letter1First} paras={c.letter1Paras} />

      {/* 7. TestimonialTriptych — three family cards (inline primitive) */}
      <div style={{ background: BG_CREAM, padding: "8px 14px 32px" }}>
        <div style={{
          textAlign: "center", fontSize: 17, color: B.ink, fontWeight: 600,
          fontStyle: "italic", lineHeight: 1.5, margin: "0 8px 18px",
        }}>
          {c.triptychIntro}
        </div>
        {c.triptychCards.map((card, i) => (
          <div key={i} style={{
            background: "#FFFFFF",
            border: `2px solid ${B.ink}`,
            borderLeft: `6px solid ${card.border_color}`,
            borderRadius: 16,
            padding: "20px 20px 22px",
            marginBottom: 14,
            boxShadow: `3px 3px 0 ${B.ink}`,
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 12 }}>
              {/* Avatar circle (no real photo — color disc) */}
              <div style={{
                width: 44, height: 44, borderRadius: "50%",
                background: card.avatar_color,
                border: `2px solid ${B.ink}`,
                flexShrink: 0,
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: 16, fontWeight: 700, color: B.ink,
              }}>
                {i + 1}
              </div>
              <div style={{
                fontSize: 10.5, letterSpacing: 1.6, textTransform: "uppercase",
                color: card.border_color, fontWeight: 700,
              }}>
                {card.label}
              </div>
            </div>
            <p style={{
              margin: "0 0 12px", fontSize: 14.5, lineHeight: 1.6, color: B.ink,
              fontStyle: "italic", fontWeight: 500,
            }}>
              &ldquo;{card.quote}&rdquo;
            </p>
            <div style={{ fontSize: 12, color: B.soft, fontWeight: 600 }}>
              — {card.by}
            </div>
          </div>
        ))}
      </div>

      {/* 8. Band: cream → mint */}
      <Band from={BG_CREAM} to={BG_MINT} height={40} />

      {/* 9. Second letter — nervous system reassurance */}
      <Letter bg={BG_MINT} first={c.letter2First} paras={c.letter2Paras} />

      {/* 10. Mechanism inline breaker — framed image */}
      <div style={{ background: BG_MINT, padding: "8px 14px 20px" }}>
        <FramedImage
          height={240}
          label={c.mechanismLabel}
          sublabel={c.mechanismSublabel}
          shadow={3}
        >
          <img
            src={c.mechanismImage}
            alt={c.mechanismAlt}
            style={{ width: "100%", height: 240, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 11. Mechanism letter (continues on mint) */}
      <Letter bg={BG_MINT} first={c.letter3First} paras={c.letter3Paras} />

      {/* 12. Band: mint → lavender */}
      <Band from={BG_MINT} to={BG_LAVENDER} height={40} />

      {/* 13. ProductShowcaseFull — product moment */}
      <div style={{ background: BG_LAVENDER, paddingBottom: 8 }}>
        <ProductShowcaseFull
          eyebrow={c.productLabel}
          title={c.productTitle}
          titleAccent={c.productTitleAccent}
          sub={c.productSub}
          priceFrom={c.productPriceFrom}
          priceNote={c.productPriceNote}
          ctaButton={c.productCta}
          features={c.productFeatures}
          ageRange={c.productAgeRange}
          microTrustText={c.productMicroTrust}
        />
      </div>

      {/* 14. Band: lavender → cream */}
      <Band from={BG_LAVENDER} to={BG_GUARANTEE} height={40} />

      {/* 15. GuaranteeBlock — full guarantee section */}
      <div style={{ background: BG_GUARANTEE, padding: "32px 22px 12px", textAlign: "center" }}>
        <Eyebrow>{c.guaranteeLabel}</Eyebrow>
        <H2 size={30} center>
          {c.guaranteeHeadline}{" "}
          <span style={{ ...B.gradientText, fontWeight: 700 }}>{c.guaranteeHeadlineAccent}</span>
        </H2>
        <p style={{
          fontSize: 15.5, color: B.soft, lineHeight: 1.55, margin: 0,
          fontWeight: 500, fontStyle: "italic",
        }}>
          {c.guaranteeSub}
        </p>
      </div>

      {/* 60-Day Seal/Badge */}
      <div style={{ background: BG_GUARANTEE, padding: "12px 14px 20px", display: "flex", justifyContent: "center" }}>
        <div style={{
          position: "relative", width: 200, height: 200,
          display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
          background: "#FFFFFF", borderRadius: "50%",
          border: `3px solid ${B.ink}`, boxShadow: `6px 6px 0 ${B.ink}`,
        }}>
          <svg width="200" height="200" viewBox="0 0 200 200" style={{ position: "absolute", inset: 0 }}>
            <defs>
              <path id="circlePathE4" d="M 100, 100 m -80, 0 a 80,80 0 1,1 160,0 a 80,80 0 1,1 -160,0" />
            </defs>
            <text fill={B.tealDeep} style={{ fontFamily: F.main, fontSize: 10, fontWeight: 700, letterSpacing: 3, textTransform: "uppercase" }}>
              <textPath href="#circlePathE4" startOffset="0">
                {c.guaranteeSealRing}
              </textPath>
            </text>
          </svg>
          <div style={{ fontSize: 11, letterSpacing: 2, textTransform: "uppercase", color: B.muted, fontWeight: 700, marginBottom: 4 }}>
            Protected by
          </div>
          <div style={{ fontSize: 56, fontWeight: 700, lineHeight: 1, ...B.gradientText }}>
            {c.guaranteeSealNumber}
          </div>
          <div style={{ fontSize: 13, fontWeight: 700, color: B.ink, letterSpacing: 0.5, marginTop: 2 }}>
            {c.guaranteeSealLabel}
          </div>
          <div style={{ fontSize: 10.5, color: B.soft, marginTop: 4, letterSpacing: 0.5 }}>
            Full refund · No forms
          </div>
        </div>
      </div>

      {/* 3 guarantee points */}
      <div style={{ background: BG_GUARANTEE, padding: "16px 14px 32px" }}>
        {c.guaranteePoints.map((p, i) => (
          <div key={i} style={{
            marginBottom: 12, background: "#FFFFFF", borderRadius: 16,
            overflow: "hidden", border: `2px solid ${B.ink}`,
            boxShadow: `3px 3px 0 ${B.ink}`,
            display: "flex", alignItems: "stretch",
          }}>
            <div style={{
              width: 42, flexShrink: 0, background: p.color,
              color: "#FFF", fontSize: 16, fontWeight: 700,
              display: "flex", alignItems: "center", justifyContent: "center",
              borderRight: `2px solid ${B.ink}`,
            }}>✓</div>
            <div style={{ padding: "14px 18px" }}>
              <div style={{ fontSize: 15, fontWeight: 700, color: B.ink, marginBottom: 6, lineHeight: 1.3 }}>
                {p.title}
              </div>
              <p style={{ margin: 0, fontSize: 13.5, lineHeight: 1.55, color: B.soft }}>{p.body}</p>
            </div>
          </div>
        ))}
      </div>

      {/* 16. CTAClose — dark ink block */}
      <CTAClose
        intro={c.ctaIntro}
        button={c.ctaButton}
        fine={c.ctaFinePrint}
        bg={BG_CTA}
      />

      {/* 17. Signoff (Lena Bauer) */}
      <Signoff bg={BG_CTA} />

      {/* 18. Footer */}
      <Footer />
    </EmailShell>
  );
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 5
// ═══════════════════════════════════════════════════════════════
const Email5 = () => {
  const c = window.FLOW_WELCOME_GF.e5;
  const B = window.BRAND;
  const F = window.FONT;

  const BG_HERO = "#FFFBF0";
  const BG_CREAM = "#FFF6E2";
  const BG_MINT = "#EAF6F2";
  const BG_GUARANTEE = "#EAF6F2";
  const BG_LAVENDER = "#F0EDF8";
  const BG_CTA = "#1F2D2F";

  return (
    <EmailShell preheader={c.preheader} bg={BG_HERO}>
      <Header bg={BG_HERO} />

      {/* 3. PartBadge (standalone) */}
      <div style={{ background: BG_HERO, padding: "24px 22px 0", textAlign: "center" }}>
        <PartBadge>{c.partBadge}</PartBadge>
      </div>

      {/* 4. TitleBlock */}
      <TitleBlock
        badge={c.heroBadge}
        part1={c.h1a}
        part2={c.h1b}
        subhead={c.heroSubhead}
      />

      {/* 5. Band: ivory → cream */}
      <Band from={BG_HERO} to={BG_CREAM} height={40} />

      {/* 6. FramedImage hero (reflective parent moment) */}
      <div style={{ background: BG_CREAM, padding: "4px 14px 24px" }}>
        <FramedImage
          height={240}
          label={c.heroLabel}
          sublabel={c.heroSublabel}
          shadow={c.heroShadow}
        >
          <img
            src={c.heroImage}
            alt={c.heroAlt}
            style={{ width: "100%", height: 240, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 7. Opening letter (warm cream) — "You've tried..." */}
      <Letter bg={BG_CREAM} first={c.letter1First} paras={c.letter1Paras} />

      {/* 8. ObjectionCalloutTriptych — 3 cards, border-left #039902 brand green */}
      <div style={{ background: BG_CREAM, padding: "8px 22px 28px" }}>
        <p style={{
          margin: "0 0 18px", fontSize: 16, lineHeight: 1.6, color: B.ink,
          fontWeight: 500, fontStyle: "italic",
        }}>
          {c.objectionIntro}
        </p>
        {c.objectionCards.map((card, i) => (
          <div key={i} style={{
            background: "#FFFFFF",
            border: `2px solid ${B.ink}`,
            borderLeft: `${c.objectionBorderWidth}px solid ${c.objectionBorderColor}`,
            borderRadius: 16,
            padding: "18px 20px 20px",
            marginBottom: 14,
            boxShadow: `3px 3px 0 ${B.ink}`,
          }}>
            <div style={{
              fontSize: 10.5, letterSpacing: 1.6, textTransform: "uppercase",
              color: c.objectionBorderColor, fontWeight: 700, marginBottom: 8,
            }}>
              {card.label}
            </div>
            <h3 style={{
              margin: "0 0 10px", fontSize: 16, fontWeight: 700,
              color: B.ink, lineHeight: 1.3,
            }}>
              {card.header}
            </h3>
            <p style={{ margin: 0, fontSize: 14, lineHeight: 1.6, color: B.soft }}>
              {card.body}
            </p>
          </div>
        ))}
      </div>

      {/* 9. Band: cream → mint */}
      <Band from={BG_CREAM} to={BG_MINT} height={40} />

      {/* 10. Reframe letter (soft mint) — "The reason nothing worked..." */}
      <Letter bg={BG_MINT} first={c.letter2First} paras={c.letter2Paras} />

      {/* 11. Mid-body inline breaker — FramedImage (potty ladder moment) */}
      <div style={{ background: BG_MINT, padding: "4px 14px 24px" }}>
        <FramedImage
          height={200}
          label={c.mechanismLabel}
          sublabel={c.mechanismSublabel}
          shadow={c.mechanismShadow}
        >
          <img
            src={c.mechanismImage}
            alt={c.mechanismAlt}
            style={{ width: "100%", height: 200, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 12. Mechanism letter (continues on mint) — "This is where BrightKidCo is different..." */}
      <Letter bg={BG_MINT} first={c.letter3First} paras={c.letter3Paras} />

      {/* 13. Band: mint → ivory (testimonial pair) */}
      <Band from={BG_MINT} to={BG_HERO} height={40} />

      {/* 14. TestimonialPair — 2 quote cards + stat strip */}
      <div style={{ background: BG_HERO, padding: "20px 14px 32px" }}>
        {c.testimonialQuotes.map((t, i) => (
          <div key={i} style={{
            background: "#FFFFFF",
            border: `2px solid ${B.ink}`,
            borderRadius: 16,
            padding: "18px 20px 20px",
            marginBottom: 12,
            boxShadow: `3px 3px 0 ${B.ink}`,
          }}>
            <p style={{
              margin: "0 0 12px", fontSize: 15, lineHeight: 1.55, color: B.ink,
              fontStyle: "italic", fontWeight: 500,
            }}>
              &ldquo;{t.quote}&rdquo;
            </p>
            <div style={{ fontSize: 12, color: B.soft, fontWeight: 600 }}>
              — {t.by}
            </div>
          </div>
        ))}
        {/* Stat strip — yellow strip card */}
        <div style={{
          background: "#FFD866",
          border: `2px solid ${B.ink}`,
          borderRadius: 12,
          padding: "12px 16px",
          marginTop: 14,
          textAlign: "center",
          boxShadow: `2px 2px 0 ${B.ink}`,
        }}>
          <p style={{ margin: 0, fontSize: 14, fontWeight: 700, color: B.ink, lineHeight: 1.4 }}>
            {c.testimonialStat}
          </p>
        </div>
      </div>

      {/* 15. Band: ivory → cream (product intro letter) */}
      <Band from={BG_HERO} to={BG_CREAM} height={40} />

      {/* 16. Product intro letter (warm cream) — bundle copy */}
      <Letter bg={BG_CREAM} first={c.letter4First} paras={c.letter4Paras} />

      {/* 17. Band: cream → lavender (product showcase) */}
      <Band from={BG_CREAM} to={BG_LAVENDER} height={40} />

      {/* 18. ProductShowcaseFull — 2 product image slots */}
      <div style={{ background: BG_LAVENDER, paddingBottom: 8 }}>
        <ProductShowcaseFull
          eyebrow={c.productLabel}
          title={c.productTitle}
          titleAccent={c.productTitleAccent}
          sub={c.productSub}
          priceFrom={c.productPriceFrom}
          priceNote={c.productPriceNote}
          ctaButton={c.productCta}
          features={c.productFeatures}
          ageRange={c.productAgeRange}
          microTrustText={c.productMicroTrust}
        />
      </div>

      {/* 19. Band: lavender → mint (guarantee) */}
      <Band from={BG_LAVENDER} to={BG_GUARANTEE} height={40} />

      {/* 20. GuaranteeBlock — eyebrow + headline + sub */}
      <div style={{ background: BG_GUARANTEE, padding: "32px 22px 12px", textAlign: "center" }}>
        <Eyebrow>{c.guaranteeLabel}</Eyebrow>
        <H2 size={30} center>
          {c.guaranteeHeadline}{" "}
          <span style={{ ...B.gradientText, fontWeight: 700 }}>{c.guaranteeHeadlineAccent}</span>
        </H2>
        <p style={{
          fontSize: 15.5, color: B.soft, lineHeight: 1.55, margin: 0,
          fontWeight: 500, fontStyle: "italic",
        }}>
          {c.guaranteeSub}
        </p>
      </div>

      {/* 60-Day circular seal */}
      <div style={{ background: BG_GUARANTEE, padding: "16px 14px 20px", display: "flex", justifyContent: "center" }}>
        <div style={{
          position: "relative", width: 200, height: 200,
          display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
          background: "#FFFFFF", borderRadius: "50%",
          border: `3px solid ${B.ink}`, boxShadow: `6px 6px 0 ${B.ink}`,
        }}>
          <svg width="200" height="200" viewBox="0 0 200 200" style={{ position: "absolute", inset: 0 }}>
            <defs>
              <path id="circlePathE5" d="M 100, 100 m -80, 0 a 80,80 0 1,1 160,0 a 80,80 0 1,1 -160,0" />
            </defs>
            <text fill={B.tealDeep} style={{ fontFamily: F.main, fontSize: 10, fontWeight: 700, letterSpacing: 3, textTransform: "uppercase" }}>
              <textPath href="#circlePathE5" startOffset="0">
                {c.guaranteeSealRing}
              </textPath>
            </text>
          </svg>
          <div style={{ fontSize: 11, letterSpacing: 2, textTransform: "uppercase", color: B.muted, fontWeight: 700, marginBottom: 4 }}>
            Protected by
          </div>
          <div style={{ fontSize: 56, fontWeight: 700, lineHeight: 1, ...B.gradientText }}>
            {c.guaranteeSealNumber}
          </div>
          <div style={{ fontSize: 13, fontWeight: 700, color: B.ink, letterSpacing: 0.5, marginTop: 2 }}>
            {c.guaranteeSealLabel}
          </div>
          <div style={{ fontSize: 10.5, color: B.soft, marginTop: 4, letterSpacing: 0.5 }}>
            Full refund · No forms
          </div>
        </div>
      </div>

      {/* 3 guarantee points (color-coded checkmark cards) */}
      <div style={{ background: BG_GUARANTEE, padding: "16px 14px 32px" }}>
        {c.guaranteePoints.map((p, i) => (
          <div key={i} style={{
            marginBottom: 12, background: "#FFFFFF", borderRadius: 16,
            overflow: "hidden", border: `2px solid ${B.ink}`,
            boxShadow: `3px 3px 0 ${B.ink}`,
            display: "flex", alignItems: "stretch",
          }}>
            <div style={{
              width: 42, flexShrink: 0, background: p.color,
              color: "#FFF", fontSize: 16, fontWeight: 700,
              display: "flex", alignItems: "center", justifyContent: "center",
              borderRight: `2px solid ${B.ink}`,
            }}>✓</div>
            <div style={{ padding: "14px 18px" }}>
              <div style={{ fontSize: 15, fontWeight: 700, color: B.ink, marginBottom: 6, lineHeight: 1.3 }}>
                {p.title}
              </div>
              <p style={{ margin: 0, fontSize: 13.5, lineHeight: 1.55, color: B.soft }}>{p.body}</p>
            </div>
          </div>
        ))}
      </div>

      {/* 21. Band: mint → ivory (CTA close lead-in) */}
      <Band from={BG_GUARANTEE} to={BG_HERO} height={40} />

      {/* 22. CustomCTA — inline CTA on dark ink with real href */}
      <div style={{ background: BG_CTA, padding: "20px 22px 44px", textAlign: "center", color: "#FFFFFF" }}>
        <p style={{ fontSize: 14, lineHeight: 1.6, color: "#B8CACD", margin: "0 0 24px" }}>
          {c.ctaIntro}
        </p>
        <a href={c.ctaHref} style={{
          display: "inline-block", padding: "17px 32px",
          background: "#D8F57C", color: B.ink, fontSize: 15.5, fontWeight: 700,
          textDecoration: "none", borderRadius: 999, letterSpacing: 0.3,
        }}>{c.ctaButton} {c.ctaButtonArrow}</a>
        <div style={{ marginTop: 16, fontSize: 11.5, color: "#8A9B9D" }}>
          {c.ctaFinePrint}
        </div>
        <div style={{ marginTop: 22, fontSize: 12, color: "#8FAFB2", fontStyle: "italic" }}>
          {c.ctaPsLine}
        </div>
      </div>

      {/* 23. Signoff (Lena Bauer) */}
      <Signoff bg={BG_CTA} />

      {/* 24. OutLine */}
      <OutLine />

      {/* Footer */}
      <Footer />
    </EmailShell>
  );
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 6
// ═══════════════════════════════════════════════════════════════
const Email6 = () => {
  const c = window.FLOW_WELCOME_GF.e6;
  const B = window.BRAND;
  const F = window.FONT;

  const BG_HERO = "#FFFBF0";
  const BG_CREAM = "#FFF6E2";
  const BG_MINT = "#EAF6F2";
  const BG_CTA = "#1F2D2F";

  return (
    <EmailShell preheader={c.preheader} bg={BG_HERO}>
      <Header bg={BG_HERO} />

      {/* 3. PartBadge (standalone) */}
      <div style={{ background: BG_HERO, padding: "24px 22px 0", textAlign: "center" }}>
        <PartBadge>{c.partBadge}</PartBadge>
      </div>

      {/* 4. StatCallout (inline JSX — NOT a primitive) */}
      {/* Hard shadow=6 (largest in palette) for visual prominence */}
      <div style={{ background: BG_HERO, padding: "12px 14px 4px" }}>
        <div style={{
          background: "#FFF6E2",
          border: "2px solid #1F2D2F",
          borderRadius: 22,
          padding: "28px 24px 26px",
          textAlign: "center",
          boxShadow: "6px 6px 0 #1F2D2F",
        }}>
          <div style={{
            fontSize: 56,
            fontWeight: 700,
            lineHeight: 1,
            color: "#D85A30",
            letterSpacing: -1.2,
            marginBottom: 6,
          }}>
            {c.statNumber}
            <span style={{ fontSize: 24, color: "#1F2D2F", fontWeight: 700, marginLeft: 4 }}>{c.statUnit}</span>
          </div>
          <div style={{
            fontSize: 14,
            fontWeight: 700,
            color: "#1F2D2F",
            letterSpacing: 0.4,
            textTransform: "uppercase",
            marginBottom: 8,
          }}>
            {c.statLabel}
          </div>
          <div style={{
            fontSize: 13.5,
            color: "#1F2D2F",
            opacity: 0.75,
            fontStyle: "italic",
            lineHeight: 1.45,
            maxWidth: 320,
            margin: "0 auto",
          }}>
            {c.statSublabel}
          </div>
        </div>
      </div>

      {/* 5. TitleBlock — "Too dry to learn." with gradient accent on part2 */}
      <TitleBlock
        badge={c.heroBadge}
        part1={c.h1a}
        part2={c.h1b}
        subhead={c.heroSubhead}
      />

      {/* 6. Band: ivory → cream */}
      <Band from={BG_HERO} to={BG_CREAM} height={40} />

      {/* 7. Hook Letter (warm cream) — "Whether your child has been in pull-ups..." */}
      <Letter bg={BG_CREAM} first={c.letter1First} paras={c.letter1Paras} />

      {/* 8. ComparisonCards (inline JSX — 2-col Pull-Ups vs BrightKidCo) */}
      <div style={{ background: BG_CREAM, padding: "4px 14px 32px" }}>
        <div style={{ textAlign: "center", marginBottom: 18 }}>
          <div style={{
            fontSize: 10.5, letterSpacing: 2, textTransform: "uppercase",
            color: "#039902", fontWeight: 700, marginBottom: 8,
          }}>
            {c.comparisonEyebrow}
          </div>
          <h2 style={{
            fontSize: 22, lineHeight: 1.2, fontWeight: 700,
            margin: "0 0 8px", letterSpacing: -0.3, color: "#1F2D2F",
          }}>
            {c.comparisonTitle}
          </h2>
          <p style={{
            fontSize: 13.5, color: "#1F2D2F", opacity: 0.75,
            fontStyle: "italic", lineHeight: 1.5, margin: 0,
            fontWeight: 500,
          }}>
            {c.comparisonSubtitle}
          </p>
        </div>

        <div style={{ display: "flex", gap: 10, alignItems: "stretch" }}>
          {/* Left card — Pull-Ups (coral ✕) */}
          <div style={{
            flex: 1, minWidth: 0,
            background: "#FFFFFF",
            border: "2px solid #1F2D2F",
            borderLeft: `6px solid ${c.comparisonLeftBorder}`,
            borderRadius: 16,
            boxShadow: "4px 4px 0 #1F2D2F",
            overflow: "hidden",
          }}>
            <div style={{
              background: c.comparisonLeftHeaderBg,
              padding: "12px 14px",
              borderBottom: "2px solid #1F2D2F",
              display: "flex", alignItems: "center", justifyContent: "space-between",
            }}>
              <div style={{
                fontSize: 15, fontWeight: 700, color: "#1F2D2F", letterSpacing: 0.2,
              }}>
                {c.comparisonLeftTitle}
              </div>
              <div style={{
                width: 28, height: 28, borderRadius: "50%",
                background: "#FFFFFF",
                border: `2px solid ${c.comparisonLeftBorder}`,
                color: c.comparisonLeftBorder,
                fontSize: 14, fontWeight: 700,
                display: "flex", alignItems: "center", justifyContent: "center",
                flexShrink: 0,
              }}>
                {c.comparisonLeftIcon}
              </div>
            </div>
            <div>
              {c.comparisonRows.map((row, i) => (
                <div key={i} style={{
                  padding: "10px 14px",
                  borderBottom: i === c.comparisonRows.length - 1 ? "none" : "1px solid #F0E6D6",
                }}>
                  <div style={{
                    fontSize: 10, letterSpacing: 1.2, textTransform: "uppercase",
                    color: "#C84B3B", fontWeight: 700, marginBottom: 3,
                  }}>
                    {row.leftLabel}
                  </div>
                  <div style={{ fontSize: 12.5, color: "#1F2D2F", lineHeight: 1.45, fontWeight: 500 }}>
                    {row.leftValue}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Right card — BrightKidCo (brand green ✓) */}
          <div style={{
            flex: 1, minWidth: 0,
            background: "#FFFFFF",
            border: "2px solid #1F2D2F",
            borderLeft: `6px solid ${c.comparisonRightBorder}`,
            borderRadius: 16,
            boxShadow: "4px 4px 0 #1F2D2F",
            overflow: "hidden",
          }}>
            <div style={{
              background: c.comparisonRightHeaderBg,
              padding: "12px 14px",
              borderBottom: "2px solid #1F2D2F",
              display: "flex", alignItems: "center", justifyContent: "space-between",
            }}>
              <div style={{
                fontSize: 15, fontWeight: 700, color: "#1F2D2F", letterSpacing: 0.2,
              }}>
                {c.comparisonRightTitle}
              </div>
              <div style={{
                width: 28, height: 28, borderRadius: "50%",
                background: "#FFFFFF",
                border: `2px solid ${c.comparisonRightBorder}`,
                color: c.comparisonRightBorder,
                fontSize: 14, fontWeight: 700,
                display: "flex", alignItems: "center", justifyContent: "center",
                flexShrink: 0,
              }}>
                {c.comparisonRightIcon}
              </div>
            </div>
            <div>
              {c.comparisonRows.map((row, i) => (
                <div key={i} style={{
                  padding: "10px 14px",
                  borderBottom: i === c.comparisonRows.length - 1 ? "none" : "1px solid #F0E6D6",
                }}>
                  <div style={{
                    fontSize: 10, letterSpacing: 1.2, textTransform: "uppercase",
                    color: "#039902", fontWeight: 700, marginBottom: 3,
                  }}>
                    {row.rightLabel}
                  </div>
                  <div style={{ fontSize: 12.5, color: "#1F2D2F", lineHeight: 1.45, fontWeight: 500 }}>
                    {row.rightValue}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* 9. Validation Letter (warm cream) — research + real-parent quote */}
      <Letter bg={BG_CREAM} first={c.letter2First} paras={c.letter2Paras} />

      {/* 10. Mechanism FramedImage — 3-layer system visual, shadow=4 */}
      <div style={{ background: BG_CREAM, padding: "4px 14px 24px" }}>
        <FramedImage
          height={240}
          label={c.mechanismLabel}
          sublabel={c.mechanismSublabel}
          shadow={4}
        >
          <img
            src={c.mechanismImage}
            alt={c.mechanismAlt}
            style={{ width: "100%", height: 240, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 11. H2 section heading — centered, size=22 */}
      <div style={{ background: BG_CREAM, padding: "4px 22px 0" }}>
        <H2 center size={22}>
          The 3-Layer <span style={{ ...B.gradientText, fontWeight: 700 }}>Body-Signal</span> Learning System
        </H2>
      </div>

      {/* Band: cream → mint */}
      <Band from={BG_CREAM} to={BG_MINT} height={40} />

      {/* 12. Mechanism Letter (soft mint) — 3-layer numbered list inside */}
      <Letter bg={BG_MINT} first={c.letter3First} paras={c.letter3Paras} />

      {/* 13. ProductShowcaseMedium — single product card on mint */}
      <div style={{ background: BG_MINT, paddingBottom: 8 }}>
        <ProductShowcaseMedium
          product={c.productName}
          image_src={c.productImage}
          price_label={c.productPriceLabel}
        />
      </div>

      {/* 14. Mid-body inline breaker FramedImage — shadow=3 */}
      <div style={{ background: BG_MINT, padding: "8px 14px 20px" }}>
        <FramedImage
          height={200}
          label={c.breakerLabel}
          sublabel={c.breakerSublabel}
          shadow={3}
        >
          <img
            src={c.breakerImage}
            alt={c.breakerAlt}
            style={{ width: "100%", height: 200, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* Band: mint → cream */}
      <Band from={BG_MINT} to={BG_CREAM} height={40} />

      {/* 15. Closing Letter (warm cream) — testimonials + guarantee + CTA copy + PS */}
      <Letter bg={BG_CREAM} first={c.letter4First} paras={c.letter4Paras} />

      {/* 16. Inline CTA — dark ink bg, lime button, real href (NOT CTAClose primitive) */}
      <div style={{ background: BG_CTA, padding: "20px 22px 44px", textAlign: "center", color: "#FFFFFF" }}>
        <a href={c.ctaHref} style={{
          display: "inline-block", padding: "17px 32px",
          background: "#D8F57C", color: B.ink, fontSize: 15.5, fontWeight: 700,
          textDecoration: "none", borderRadius: 999, letterSpacing: 0.3,
          boxShadow: `4px 4px 0 ${"#FFFFFF"}`,
        }}>{c.ctaButton} {c.ctaButtonArrow}</a>
      </div>

      {/* 17. Signoff (Lena Bauer) */}
      <Signoff bg={BG_CTA} />

      {/* Footer */}
      <Footer />
    </EmailShell>
  );
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 7
// ═══════════════════════════════════════════════════════════════
const Email7 = () => {
  const c = window.FLOW_WELCOME_GF.e7;
  const B = window.BRAND;
  const F = window.FONT;

  const BG_HERO = "#FFFBF0";
  const BG_CREAM = "#FFF6E2";
  const BG_OFFWHITE = "#FAF7F2";
  const BG_TEAL_SOFT = "#EAF6F2";
  const BG_LAVENDER = "#F0EDF8";
  const BG_GUARANTEE = "#FFFBF0";
  const BG_CTA = "#1F2D2F";

  // LayerRow primitive — inline (not yet in shared primitives.jsx).
  // Vertical stack of 3 layer rows for the Body-Signal Learning Layer
  // mechanism explainer. Each row carries layer_number, title, icon, icon_color,
  // duration badge, body copy, and a left-border accent in the layer's brand
  // color (Amber #E8923C, Soft Beige #D9C6A8, Muted Teal #5B9B8A).
  const LayerRow = ({ rows, bg }) => (
    <div style={{ background: bg, padding: "8px 14px 28px" }}>
      {rows.map((row, i) => (
        <div key={i} style={{
          display: "flex",
          gap: 14,
          background: "#FFFFFF",
          border: `2px solid ${B.ink}`,
          borderLeft: `6px solid ${row.accent_border}`,
          borderRadius: 16,
          padding: "18px 20px 20px",
          marginBottom: 14,
          boxShadow: `3px 3px 0 ${B.ink}`,
        }}>
          {/* Left icon column */}
          <div style={{
            width: 52, height: 52, flexShrink: 0,
            borderRadius: 14,
            background: row.icon_color,
            border: `2px solid ${B.ink}`,
            display: "flex", alignItems: "center", justifyContent: "center",
            fontSize: 18, fontWeight: 700, color: B.ink,
          }}>
            {row.icon === "amber_dot" && "\u25cf"}
            {row.icon === "beige_wave" && "\u223f"}
            {row.icon === "teal_shield" && "\u25b2"}
          </div>

          {/* Right content column */}
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{
              display: "flex", alignItems: "center", gap: 8, marginBottom: 6,
              flexWrap: "wrap",
            }}>
              <div style={{
                fontSize: 10, letterSpacing: 1.4, textTransform: "uppercase",
                color: row.accent_border, fontWeight: 700,
              }}>
                {row.layer_number}
              </div>
              <div style={{
                fontSize: 9.5, letterSpacing: 1, textTransform: "uppercase",
                color: B.muted, fontWeight: 700,
                background: `${row.accent_border}22`,
                padding: "3px 8px",
                borderRadius: 999,
              }}>
                {row.duration}
              </div>
            </div>
            <h3 style={{
              margin: "0 0 8px", fontSize: 16, fontWeight: 700,
              color: B.ink, lineHeight: 1.3,
            }}>
              {row.title}
            </h3>
            <p style={{ margin: 0, fontSize: 13.5, lineHeight: 1.6, color: B.soft }}>
              {row.body}
            </p>
          </div>
        </div>
      ))}
    </div>
  );

  // TestimonialQuintet primitive — inline (not yet in shared primitives.jsx).
  // 5 quote cards arranged with alternating left/right indent pattern
  // (left, right, left, right, left) which DIFFERS from e3's 3-family triptych
  // in FramedImage and e4's TestimonialTriptych 3-card horizontal row. Each
  // card has a level tag (L1/L2/Cross/L3) and a distinct left-border color
  // drawn from the level-coded family (Coral #E8A98F, Teal #8AB9B5, Gold
  // #D4B886, Muted Lavender #B0A0C0).
  const TestimonialQuintet = ({ cards, intro, bg }) => (
    <div style={{ background: bg, padding: "8px 14px 28px" }}>
      <div style={{
        textAlign: "center", fontSize: 16, color: B.ink, fontWeight: 600,
        fontStyle: "italic", lineHeight: 1.5, margin: "0 8px 18px",
      }}>
        {intro}
      </div>
      {cards.map((card, i) => {
        const isLeft = card.indent === "left";
        return (
          <div key={i} style={{
            background: "#FFFFFF",
            border: `2px solid ${B.ink}`,
            borderLeft: `6px solid ${card.border_color}`,
            borderRadius: 16,
            padding: "18px 20px 20px",
            marginBottom: 14,
            marginLeft: isLeft ? 0 : 28,
            marginRight: isLeft ? 28 : 0,
            boxShadow: `3px 3px 0 ${B.ink}`,
          }}>
            <div style={{
              display: "flex", alignItems: "center", gap: 10, marginBottom: 10,
            }}>
              <div style={{
                fontSize: 10, letterSpacing: 1.4, textTransform: "uppercase",
                color: card.border_color, fontWeight: 700,
              }}>
                {card.label}
              </div>
              <div style={{
                fontSize: 9.5, letterSpacing: 1, textTransform: "uppercase",
                color: B.muted, fontWeight: 700,
                background: `${card.border_color}22`,
                padding: "3px 8px",
                borderRadius: 999,
              }}>
                {card.level_tag}
              </div>
            </div>
            <p style={{
              margin: "0 0 10px", fontSize: 14.5, lineHeight: 1.6, color: B.ink,
              fontStyle: "italic", fontWeight: 500,
            }}>
              &ldquo;{card.quote}&rdquo;
            </p>
            <div style={{ fontSize: 12, color: B.soft, fontWeight: 600 }}>
              — {card.by}
            </div>
          </div>
        );
      })}
    </div>
  );

  return (
    <EmailShell preheader={c.preheader} bg={BG_HERO}>
      <Header bg={BG_HERO} />

      {/* 3. PartBadge (standalone) */}
      <div style={{ background: BG_HERO, padding: "24px 22px 0", textAlign: "center" }}>
        <PartBadge>{c.partBadge}</PartBadge>
      </div>

      {/* 4. TitleBlock */}
      <TitleBlock
        badge={c.heroBadge}
        part1={c.h1a}
        part2={c.h1b}
        subhead={c.heroSubhead}
      />

      {/* 5. Band: ivory → cream */}
      <Band from={BG_HERO} to={BG_CREAM} height={40} />

      {/* 6. Hook letter (warm cream) — *why* italicized */}
      <Letter bg={BG_CREAM} first={c.letter1First} paras={c.letter1Paras} />

      {/* 7. FramedImage (validation hero breaker) */}
      <div style={{ background: BG_CREAM, padding: "4px 14px 24px" }}>
        <FramedImage
          height={260}
          label={c.validationImageLabel}
          sublabel={c.validationImageSublabel}
          shadow={c.validationImageShadow}
        >
          <img
            src={c.validationImage}
            alt={c.validationImageAlt}
            style={{ width: "100%", height: 260, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 8. Validation letter (4px Warm Amber #E8923C left-border treatment) */}
      <div style={{
        background: BG_HERO,
        borderLeft: c.validationBorderLeft,
        paddingLeft: c.validationPaddingLeft,
        paddingRight: 24,
        paddingTop: 4,
        paddingBottom: 28,
        fontSize: 15, lineHeight: 1.7, color: B.soft,
      }}>
        <p style={{ margin: "0 0 14px", fontSize: 17, color: B.ink, fontWeight: 600 }}>
          {c.letter2First}
        </p>
        {c.letter2Paras.map((p, i) => (
          <p key={i} style={{ margin: i === c.letter2Paras.length - 1 ? 0 : "0 0 14px" }}>
            {p}
          </p>
        ))}
      </div>

      {/* 9. Mechanism eyebrow */}
      <div style={{ background: BG_HERO, padding: "16px 22px 0", textAlign: "center" }}>
        <Eyebrow color={c.mechanismEyebrowColor}>{c.mechanismEyebrow}</Eyebrow>
      </div>

      {/* 10. Mechanism H2 */}
      <div style={{ background: BG_HERO, padding: "0 22px 16px", textAlign: "center" }}>
        <H2 center size={22}>{c.mechanismH2}</H2>
      </div>

      {/* 11. Band: ivory → off-white (mechanism section bg) */}
      <Band from={BG_HERO} to={BG_OFFWHITE} height={40} />

      {/* 12. Mechanism lead letter (off-white) — core insight */}
      <Letter bg={BG_OFFWHITE} first={c.letter3First} paras={c.letter3Paras} />

      {/* 13. LayerRow — 3-layer Body-Signal Learning Layer explainer (off-white) */}
      <LayerRow rows={c.layerRows} bg={BG_OFFWHITE} />

      {/* 14. Band: off-white → pale teal (metaphor closer) */}
      <Band from={BG_OFFWHITE} to={BG_TEAL_SOFT} height={40} />

      {/* 15. Mechanism metaphor closer letter (pale teal) — training wheels */}
      <Letter bg={BG_TEAL_SOFT} first={c.letter4First} paras={c.letter4Paras} />

      {/* 16. Band: pale teal → ivory (testimonials) */}
      <Band from={BG_TEAL_SOFT} to={BG_HERO} height={40} />

      {/* 17. Testimonials eyebrow */}
      <div style={{ background: BG_HERO, padding: "20px 22px 0", textAlign: "center" }}>
        <Eyebrow color={c.testimonialsEyebrowColor}>{c.testimonialsEyebrow}</Eyebrow>
      </div>

      {/* 18. TestimonialQuintet — 5 mini-win cards, alternating left/right indent */}
      <TestimonialQuintet
        cards={c.testimonials}
        intro={c.testimonialsIntro}
        bg={BG_HERO}
      />

      {/* 19. Band: ivory → cream (testimonials closing) */}
      <Band from={BG_HERO} to={BG_CREAM} height={40} />

      {/* 20. Testimonials closing letter (warm cream) — common thread */}
      <Letter bg={BG_CREAM} first={c.letter5First} paras={c.letter5Paras} />

      {/* 21. FramedImage product hero (flat-lay, shadow=4) */}
      <div style={{ background: BG_CREAM, padding: "4px 14px 24px" }}>
        <FramedImage
          height={260}
          label={c.productHeroImageLabel}
          sublabel={c.productHeroImageSublabel}
          shadow={c.productHeroImageShadow}
        >
          <img
            src={c.productHeroImage}
            alt={c.productHeroImageAlt}
            style={{ width: "100%", height: 260, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 22. Band: cream → lavender (product showcase) */}
      <Band from={BG_CREAM} to={BG_LAVENDER} height={40} />

      {/* 23. ProductShowcaseFull — 2 product image slots */}
      <div style={{ background: BG_LAVENDER, paddingBottom: 8 }}>
        <ProductShowcaseFull
          eyebrow={c.productLabel}
          title={c.productTitle}
          titleAccent={c.productTitleAccent}
          sub={c.productSub}
          priceFrom={c.productPriceFrom}
          priceNote={c.productPriceNote}
          ctaButton={c.productCta}
          features={c.productFeatures}
          ageRange={c.productAgeRange}
          microTrustText={c.productMicroTrust}
        />
      </div>

      {/* 24. Band: lavender → ivory (product bullets + guarantee) */}
      <Band from={BG_LAVENDER} to={BG_HERO} height={40} />

      {/* 25. Product bullets letter (ivory) — what you get + 1-pair secondary */}
      <Letter bg={BG_HERO} first={c.letter6First} paras={c.letter6Paras} />

      {/* 26. GuaranteeBlock — eyebrow + headline + sub */}
      <div style={{ background: BG_GUARANTEE, padding: "32px 22px 12px", textAlign: "center" }}>
        <Eyebrow>{c.guaranteeLabel}</Eyebrow>
        <H2 size={30} center>
          {c.guaranteeHeadline}{" "}
          <span style={{ ...B.gradientText, fontWeight: 700 }}>{c.guaranteeHeadlineAccent}</span>
        </H2>
        <p style={{
          fontSize: 15.5, color: B.soft, lineHeight: 1.55, margin: 0,
          fontWeight: 500, fontStyle: "italic",
        }}>
          {c.guaranteeSub}
        </p>
      </div>

      {/* 27. 60-Day circular seal */}
      <div style={{ background: BG_GUARANTEE, padding: "16px 14px 20px", display: "flex", justifyContent: "center" }}>
        <div style={{
          position: "relative", width: 200, height: 200,
          display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
          background: "#FFFFFF", borderRadius: "50%",
          border: `3px solid ${B.ink}`, boxShadow: `6px 6px 0 ${B.ink}`,
        }}>
          <svg width="200" height="200" viewBox="0 0 200 200" style={{ position: "absolute", inset: 0 }}>
            <defs>
              <path id="circlePathE7" d="M 100, 100 m -80, 0 a 80,80 0 1,1 160,0 a 80,80 0 1,1 -160,0" />
            </defs>
            <text fill={B.tealDeep} style={{ fontFamily: F.main, fontSize: 10, fontWeight: 700, letterSpacing: 3, textTransform: "uppercase" }}>
              <textPath href="#circlePathE7" startOffset="0">
                {c.guaranteeSealRing}
              </textPath>
            </text>
          </svg>
          <div style={{ fontSize: 11, letterSpacing: 2, textTransform: "uppercase", color: B.muted, fontWeight: 700, marginBottom: 4 }}>
            Protected by
          </div>
          <div style={{ fontSize: 56, fontWeight: 700, lineHeight: 1, ...B.gradientText }}>
            {c.guaranteeSealNumber}
          </div>
          <div style={{ fontSize: 13, fontWeight: 700, color: B.ink, letterSpacing: 0.5, marginTop: 2 }}>
            {c.guaranteeSealLabel}
          </div>
          <div style={{ fontSize: 10.5, color: B.soft, marginTop: 4, letterSpacing: 0.5 }}>
            Full refund · No forms
          </div>
        </div>
      </div>

      {/* 28. 3 guarantee points (color-coded checkmark cards) */}
      <div style={{ background: BG_GUARANTEE, padding: "16px 14px 24px" }}>
        {c.guaranteePoints.map((p, i) => (
          <div key={i} style={{
            marginBottom: 12, background: "#FFFFFF", borderRadius: 16,
            overflow: "hidden", border: `2px solid ${B.ink}`,
            boxShadow: `3px 3px 0 ${B.ink}`,
            display: "flex", alignItems: "stretch",
          }}>
            <div style={{
              width: 42, flexShrink: 0, background: p.color,
              color: "#FFF", fontSize: 16, fontWeight: 700,
              display: "flex", alignItems: "center", justifyContent: "center",
              borderRight: `2px solid ${B.ink}`,
            }}>✓</div>
            <div style={{ padding: "14px 18px" }}>
              <div style={{ fontSize: 15, fontWeight: 700, color: B.ink, marginBottom: 6, lineHeight: 1.3 }}>
                {p.title}
              </div>
              <p style={{ margin: 0, fontSize: 13.5, lineHeight: 1.55, color: B.soft }}>{p.body}</p>
            </div>
          </div>
        ))}
      </div>

      {/* 29. Guarantee closer letter (ivory) */}
      <div style={{ background: BG_GUARANTEE, padding: "4px 24px 28px", fontSize: 15, lineHeight: 1.7, color: B.soft }}>
        <p style={{ margin: 0, fontSize: 15, color: B.ink, fontWeight: 500, fontStyle: "italic" }}>
          {c.guaranteeCloser}
        </p>
      </div>

      {/* 30. CTA H2 */}
      <div style={{ background: BG_HERO, padding: "28px 22px 12px", textAlign: "center" }}>
        <H2 center size={20}>{c.ctaH2}</H2>
      </div>

      {/* 31. Band: ivory → ink (CTA) */}
      <Band from={BG_HERO} to={BG_CTA} height={40} />

      {/* 32. CustomCTA — inline CTA on dark ink with real href + secondary link + PS line */}
      <div style={{ background: BG_CTA, padding: "20px 22px 44px", textAlign: "center", color: "#FFFFFF" }}>
        <p style={{ fontSize: 14, lineHeight: 1.6, color: "#B8CACD", margin: "0 0 24px" }}>
          {c.ctaIntro}
        </p>
        <a href={c.ctaHref} style={{
          display: "inline-block", padding: "17px 32px",
          background: "#D8F57C", color: B.ink, fontSize: 15.5, fontWeight: 700,
          textDecoration: "none", borderRadius: 999, letterSpacing: 0.3,
        }}>{c.ctaButton} {c.ctaButtonArrow}</a>
        <div style={{ marginTop: 16, fontSize: 11.5, color: "#8A9B9D" }}>
          {c.ctaFinePrint}
        </div>
        <div style={{ marginTop: 18, fontSize: 12.5, color: "#D8F57C" }}>
          <a href={c.ctaSecondaryHref} style={{ color: "#D8F57C", textDecoration: "underline", fontWeight: 600 }}>
            {c.ctaSecondaryLink}
          </a>
        </div>
        <div style={{ marginTop: 12, fontSize: 11.5, color: "#8A9B9D", fontStyle: "italic" }}>
          {c.ctaPriceNote}
        </div>
        <div style={{ marginTop: 22, fontSize: 12, color: "#8FAFB2", fontStyle: "italic" }}>
          {c.ctaPsLine}
        </div>
      </div>

      {/* 33. Signoff (Lena Bauer) — LONG variant */}
      <Signoff bg={BG_CTA} />

      {/* 34. Footer */}
      <Footer />
    </EmailShell>
  );
};

// ═══════════════════════════════════════════════════════════════
// EMAIL 8
// ═══════════════════════════════════════════════════════════════
const Email8 = () => {
  const c = window.FLOW_WELCOME_GF.e8;
  const B = window.BRAND;
  const F = window.FONT;

  // GF color palette (warm stone → dusk gold)
  const BG_HERO = "#FFFBF0";        // warm ivory
  const BG_CREAM = "#FFF6E2";       // warm cream
  const BG_STONE = "#F0EAE1";       // warm stone (recap card bg)
  const BG_TEAL = "#EAF6F2";        // soft teal (guarantee)
  const BG_GOLD = "#D4A76A";        // dusk gold (accent)
  const BG_CTA = "#1F2D2F";         // dark teal/ink (signoff)
  const INK = "#1F2D2F";            // primary ink for borders/text on cream

  return (
    <EmailShell preheader={c.preheader} bg={BG_HERO}>
      <Header bg={BG_HERO} />

      {/* 3. PartBadge (standalone) — yellow tilted pill, rotate(-1.5deg) */}
      <div style={{ background: BG_HERO, padding: "24px 22px 0", textAlign: "center" }}>
        <PartBadge>{c.partBadge}</PartBadge>
      </div>

      {/* 4. TitleBlock — Part 8 of 8 · Day 21 with gradient accent on part2 */}
      <TitleBlock
        badge={c.heroBadge}
        part1={c.h1a}
        part2={c.h1b}
        subhead={c.heroSubhead}
      />

      {/* 5. Band: ivory → cream (transition into hook) */}
      <Band from={BG_HERO} to={BG_CREAM} height={40} />

      {/* 6. Hook Letter (warm cream) — "You've been reading these emails..." */}
      <Letter bg={BG_CREAM} first={c.letterHookFirst} paras={c.letterHookParas} />

      {/* 7. Recap lead visual (rearview open field) — FramedImage, hard shadow=6 */}
      <div style={{ background: BG_CREAM, padding: "4px 14px 24px" }}>
        <FramedImage
          height={240}
          label={c.recapLeadLabel}
          sublabel={c.recapLeadSublabel}
          shadow={c.recapLeadShadow}
        >
          <img
            src={c.recapLeadImage}
            alt={c.recapLeadAlt}
            style={{ width: "100%", height: 240, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 8. H2 — recap section heading (centered, size=22) */}
      <div style={{ background: BG_CREAM, padding: "4px 22px 12px" }}>
        <H2 center size={22}>
          21 days, four <span style={{ ...B.gradientText, fontWeight: 700 }}>big ideas</span>
        </H2>
      </div>

      {/* 9-12. RecapCard × 4 — 2x2 grid, warm stone bg, 2px ink border, shadow=4 */}
      <div style={{ background: BG_CREAM, padding: "0 14px 24px" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
          {c.recapCards.map((card, i) => (
            <div key={i} style={{
              background: BG_STONE,
              border: `2px solid ${INK}`,
              borderRadius: 14,
              padding: "14px 14px 16px",
              boxShadow: `4px 4px 0 ${INK}`,
            }}>
              <div style={{
                fontSize: 9.5, letterSpacing: 1.2, textTransform: "uppercase",
                color: BG_GOLD, fontWeight: 700, marginBottom: 8,
                display: "flex", alignItems: "center", gap: 6,
              }}>
                <span style={{ fontSize: 16 }}>{card.icon}</span>
                <span>{card.label}</span>
              </div>
              <h3 style={{
                margin: "0 0 8px", fontSize: 13, fontWeight: 700,
                color: INK, lineHeight: 1.3, letterSpacing: -0.1,
              }}>
                {card.title}
              </h3>
              <p style={{ margin: 0, fontSize: 11.5, lineHeight: 1.5, color: INK, opacity: 0.78 }}>
                {card.body}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* 13. Recap inline breaker — FramedImage, hard shadow=3 */}
      <div style={{ background: BG_CREAM, padding: "4px 14px 24px" }}>
        <FramedImage
          height={200}
          label={c.recapBreakerLabel}
          sublabel={c.recapBreakerSublabel}
          shadow={c.recapBreakerShadow}
        >
          <img
            src={c.recapBreakerImage}
            alt={c.recapBreakerAlt}
            style={{ width: "100%", height: 200, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* Recap closing paragraph */}
      <div style={{ background: BG_CREAM, padding: "0 24px 28px", fontSize: 14.5, lineHeight: 1.7, color: B.soft }}>
        <p style={{ margin: 0, fontStyle: "italic" }}>{c.recapClosing}</p>
      </div>

      {/* 14. MigrationAnchorCard — 3px gold border, quiz link, constellation easter egg */}
      <div style={{ background: BG_CREAM, padding: "0 14px 32px" }}>
        <div style={{
          position: "relative",
          background: "#FFFBF0",
          border: `3px solid ${BG_GOLD}`,
          borderRadius: 16,
          padding: "22px 22px 24px",
          boxShadow: `4px 4px 0 ${INK}`,
          overflow: "hidden",
        }}>
          {/* Constellation easter-egg SVG — 5 dots forming a ~315° incomplete circle
              (incomplete at top-right, ~45° gap as the invitation to complete) */}
          <svg
            width="200"
            height="60"
            viewBox="0 0 200 60"
            style={{ position: "absolute", bottom: 8, right: 8, opacity: 0.25, pointerEvents: "none" }}
          >
            {/* arc: 315° of a circle, starting at top (12 o'clock) sweeping clockwise to right side
                with a 45° gap at top-right */}
            <path
              d="M 145,15 A 45,45 0 1,0 100,15"
              stroke={BG_GOLD}
              strokeWidth="1"
              fill="none"
              strokeDasharray="4,3"
            />
            {/* 5 dots representing the 5 GF sub-groups (A through E) */}
            <circle cx="100" cy="15" r="2.5" fill={BG_GOLD} />
            <circle cx="55"  cy="15" r="2.5" fill={BG_GOLD} />
            <circle cx="55"  cy="60" r="2.5" fill={BG_GOLD} />
            <circle cx="100" cy="60" r="2.5" fill={BG_GOLD} />
            <circle cx="145" cy="60" r="2.5" fill={BG_GOLD} />
          </svg>

          {/* eyebrow */}
          <div style={{
            fontSize: 10.5, letterSpacing: 1.8, textTransform: "uppercase",
            color: BG_GOLD, fontWeight: 700, marginBottom: 10,
          }}>
            {c.migrationEyebrow}
          </div>

          {/* headline with gradient accent on "more detailed assessment" */}
          <h3 style={{
            margin: "0 0 12px", fontSize: 17, fontWeight: 700,
            color: INK, lineHeight: 1.35, letterSpacing: -0.2,
          }}>
            If your child sounds like any of these descriptions, click here for a{" "}
            <span style={{ ...B.gradientText, fontWeight: 700 }}>
              more detailed assessment
            </span>.
          </h3>

          {/* body lead */}
          <p style={{
            margin: "0 0 18px", fontSize: 13.5, lineHeight: 1.6,
            color: B.soft,
          }}>
            {c.migrationBodyLead}
          </p>

          {/* inline CTA button */}
          <a href={c.migrationCtaHref} style={{
            display: "inline-block", padding: "13px 26px",
            background: INK, color: "#D8F57C", fontSize: 14, fontWeight: 700,
            textDecoration: "none", borderRadius: 999, letterSpacing: 0.3,
            boxShadow: `3px 3px 0 ${BG_GOLD}`,
          }}>
            {c.migrationCtaLabel} {c.migrationCtaArrow}
          </a>
        </div>
      </div>

      {/* 15. Band: cream → cream (no visual change, but soft transition) */}
      <Band from={BG_CREAM} to={BG_CREAM} height={40} />

      {/* 16. H2 — offer section heading (centered, size=24) */}
      <div style={{ background: BG_CREAM, padding: "20px 22px 8px" }}>
        <H2 center size={24}>
          This the <span style={{ ...B.gradientText, fontWeight: 700 }}>only</span> offer we make
        </H2>
      </div>

      {/* 17. OfferCard — 1 Pair (primary) — hard shadow=6 */}
      <div style={{ background: BG_CREAM, padding: "12px 14px 8px" }}>
        <div style={{
          background: "#FFF6E2",
          border: `2px solid ${INK}`,
          borderRadius: 18,
          padding: "22px 22px 24px",
          boxShadow: `6px 6px 0 ${INK}`,
        }}>
          {/* eyebrow */}
          <div style={{
            fontSize: 10.5, letterSpacing: 1.8, textTransform: "uppercase",
            color: BG_GOLD, fontWeight: 700, marginBottom: 8,
          }}>
            {c.offerPrimaryEyebrow}
          </div>

          {/* label (1 PAIR) */}
          <div style={{
            fontSize: 12, letterSpacing: 1.6, textTransform: "uppercase",
            color: INK, fontWeight: 700, marginBottom: 6,
          }}>
            {c.offerPrimaryLabel}
          </div>

          {/* price (large light-weight numeric) */}
          <div style={{
            fontSize: 28, fontWeight: 300, lineHeight: 1,
            color: INK, marginBottom: 12, letterSpacing: -0.4,
          }}>
            {c.offerPrimaryPrice}
          </div>

          {/* line one — guarantee highlight */}
          <div style={{
            fontSize: 14, fontWeight: 700, color: INK,
            lineHeight: 1.35, marginBottom: 8,
          }}>
            {c.offerPrimaryLineOne}
          </div>

          {/* line two — body copy */}
          <p style={{
            margin: "0 0 20px", fontSize: 13.5, lineHeight: 1.6,
            color: B.soft,
          }}>
            {c.offerPrimaryLineTwo}
          </p>

          {/* inline CTA button */}
          <a href={c.offerPrimaryCtaHref} style={{
            display: "inline-block", padding: "17px 32px",
            background: INK, color: "#D8F57C", fontSize: 15, fontWeight: 700,
            textDecoration: "none", borderRadius: 999, letterSpacing: 0.3,
            marginBottom: 14,
          }}>
            {c.offerPrimaryCtaLabel} {c.offerPrimaryCtaArrow}
          </a>

          {/* whisper line — italic, lighter grey, 13px */}
          <div style={{
            fontSize: 13, color: "#8A8A8A", fontStyle: "italic", marginTop: 4,
          }}>
            {c.offerPrimaryWhisper}
          </div>
        </div>
      </div>

      {/* 18. OfferSeparator — soft gold hr with "or" in the middle */}
      <div style={{ background: BG_CREAM, padding: "20px 14px" }}>
        <div style={{
          display: "flex", alignItems: "center", justifyContent: "center", gap: 14,
        }}>
          <hr style={{
            border: "none", borderTop: `1px solid ${BG_GOLD}`,
            opacity: 0.3, width: 60, margin: 0,
          }} />
          <div style={{
            fontSize: 13, color: BG_GOLD, fontStyle: "italic", fontWeight: 500,
            letterSpacing: 0.5,
          }}>
            {c.offerSeparatorText}
          </div>
          <hr style={{
            border: "none", borderTop: `1px solid ${BG_GOLD}`,
            opacity: 0.3, width: 60, margin: 0,
          }} />
        </div>
      </div>

      {/* 19. OfferCard — 3+3 Bundle (secondary) — hard shadow=3 */}
      <div style={{ background: BG_CREAM, padding: "0 14px 8px" }}>
        <div style={{
          background: "#FFF6E2",
          border: `2px solid ${INK}`,
          borderRadius: 18,
          padding: "22px 22px 24px",
          boxShadow: `3px 3px 0 ${INK}`,
        }}>
          {/* eyebrow */}
          <div style={{
            fontSize: 10.5, letterSpacing: 1.8, textTransform: "uppercase",
            color: BG_GOLD, fontWeight: 700, marginBottom: 8,
          }}>
            {c.offerSecondaryEyebrow}
          </div>

          {/* label (3+3 BUNDLE) */}
          <div style={{
            fontSize: 12, letterSpacing: 1.6, textTransform: "uppercase",
            color: INK, fontWeight: 700, marginBottom: 6,
          }}>
            {c.offerSecondaryLabel}
          </div>

          {/* price (large light-weight numeric) */}
          <div style={{
            fontSize: 28, fontWeight: 300, lineHeight: 1,
            color: INK, marginBottom: 12, letterSpacing: -0.4,
          }}>
            {c.offerSecondaryPrice}
          </div>

          {/* line one — free shipping highlight */}
          <div style={{
            fontSize: 14, fontWeight: 700, color: INK,
            lineHeight: 1.35, marginBottom: 14,
          }}>
            {c.offerSecondaryLineOne}
          </div>

          {/* Why 3+3? rationale block */}
          <div style={{
            background: "#FFFBF0",
            borderLeft: `3px solid ${BG_GOLD}`,
            borderRadius: 8,
            padding: "12px 14px",
            marginBottom: 14,
          }}>
            <div style={{
              fontSize: 13, fontWeight: 700, color: INK,
              marginBottom: 6, letterSpacing: -0.1,
            }}>
              {c.offerSecondaryRationaleHeading}
            </div>
            <p style={{
              margin: 0, fontSize: 12.5, lineHeight: 1.55, color: B.soft,
            }}>
              {c.offerSecondaryRationaleBody}
            </p>
          </div>

          {/* price-comparison line — italic gold */}
          <p style={{
            margin: "0 0 18px", fontSize: 13, lineHeight: 1.55,
            color: BG_GOLD, fontStyle: "italic", fontWeight: 600,
          }}>
            {c.offerSecondaryComparisonLine}
          </p>

          {/* inline CTA button */}
          <a href={c.offerSecondaryCtaHref} style={{
            display: "inline-block", padding: "17px 32px",
            background: INK, color: "#D8F57C", fontSize: 15, fontWeight: 700,
            textDecoration: "none", borderRadius: 999, letterSpacing: 0.3,
          }}>
            {c.offerSecondaryCtaLabel} {c.offerSecondaryCtaArrow}
          </a>
        </div>
      </div>

      {/* 20. Offer inline product visual — FramedImage, hard shadow=3 */}
      <div style={{ background: BG_CREAM, padding: "16px 14px 28px" }}>
        <FramedImage
          height={200}
          label={c.offerProductLabel}
          sublabel={c.offerProductSublabel}
          shadow={c.offerProductShadow}
        >
          <img
            src={c.offerProductImage}
            alt={c.offerProductAlt}
            style={{ width: "100%", height: 200, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 21. Band: cream → teal (transition into guarantee) */}
      <Band from={BG_CREAM} to={BG_TEAL} height={40} />

      {/* 22. H2 — guarantee section heading (centered, size=24) */}
      <div style={{ background: BG_TEAL, padding: "24px 22px 4px", textAlign: "center" }}>
        <H2 center size={24}>
          <span style={{ ...B.gradientText, fontWeight: 700 }}>60 days.</span> By your judgment.
        </H2>
      </div>

      {/* 23. GuaranteeBlock — eyebrow + headline + sub + seal + 3 points */}
      <div style={{ background: BG_TEAL, padding: "20px 22px 12px", textAlign: "center" }}>
        <Eyebrow color={B.tealDeep}>{c.guaranteeLabel}</Eyebrow>
        <h2 style={{
          fontSize: 26, lineHeight: 1.15, fontWeight: 700,
          margin: "0 0 14px", letterSpacing: -0.4,
        }}>
          {c.guaranteeHeadline.split(".")[0]}.{" "}
          <span style={{ ...B.gradientText, fontWeight: 700 }}>
            {c.guaranteeHeadlineAccent}.
          </span>
        </h2>
        <p style={{
          fontSize: 15, color: B.soft, lineHeight: 1.6, margin: 0,
          fontWeight: 500, fontStyle: "italic",
        }}>
          {c.guaranteeSub}
        </p>
      </div>

      {/* 60-Day circular seal */}
      <div style={{ background: BG_TEAL, padding: "16px 14px 20px", display: "flex", justifyContent: "center" }}>
        <div style={{
          position: "relative", width: 200, height: 200,
          display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
          background: "#FFFFFF", borderRadius: "50%",
          border: `3px solid ${INK}`, boxShadow: `6px 6px 0 ${INK}`,
        }}>
          <svg width="200" height="200" viewBox="0 0 200 200" style={{ position: "absolute", inset: 0 }}>
            <defs>
              <path id="circlePathE8" d="M 100, 100 m -80, 0 a 80,80 0 1,1 160,0 a 80,80 0 1,1 -160,0" />
            </defs>
            <text fill={B.tealDeep} style={{ fontFamily: F.main, fontSize: 10, fontWeight: 700, letterSpacing: 3, textTransform: "uppercase" }}>
              <textPath href="#circlePathE8" startOffset="0">
                {c.guaranteeSealRing}
              </textPath>
            </text>
          </svg>
          <div style={{ fontSize: 11, letterSpacing: 2, textTransform: "uppercase", color: B.muted, fontWeight: 700, marginBottom: 4 }}>
            Protected by
          </div>
          <div style={{ fontSize: 56, fontWeight: 700, lineHeight: 1, ...B.gradientText }}>
            {c.guaranteeSealNumber}
          </div>
          <div style={{ fontSize: 13, fontWeight: 700, color: INK, letterSpacing: 0.5, marginTop: 2 }}>
            {c.guaranteeSealLabel}
          </div>
          <div style={{ fontSize: 10.5, color: B.soft, marginTop: 4, letterSpacing: 0.5 }}>
            Full refund · No forms
          </div>
        </div>
      </div>

      {/* 3 guarantee points (color-coded checkmark cards) */}
      <div style={{ background: BG_TEAL, padding: "16px 14px 32px" }}>
        {c.guaranteePoints.map((p, i) => (
          <div key={i} style={{
            marginBottom: 12, background: "#FFFFFF", borderRadius: 16,
            overflow: "hidden", border: `2px solid ${INK}`,
            boxShadow: `3px 3px 0 ${INK}`,
            display: "flex", alignItems: "stretch",
          }}>
            <div style={{
              width: 42, flexShrink: 0, background: p.color,
              color: "#FFF", fontSize: 16, fontWeight: 700,
              display: "flex", alignItems: "center", justifyContent: "center",
              borderRight: `2px solid ${INK}`,
            }}>✓</div>
            <div style={{ padding: "14px 18px" }}>
              <div style={{ fontSize: 15, fontWeight: 700, color: INK, marginBottom: 6, lineHeight: 1.3 }}>
                {p.title}
              </div>
              <p style={{ margin: 0, fontSize: 13.5, lineHeight: 1.55, color: B.soft }}>{p.body}</p>
            </div>
          </div>
        ))}
      </div>

      {/* 24. Band: teal → cream (transition into signoff) */}
      <Band from={BG_TEAL} to={BG_HERO} height={40} />

      {/* 25. Soft close inline breaker — FramedImage (washing machine), hard shadow=3 */}
      <div style={{ background: BG_HERO, padding: "4px 14px 24px" }}>
        <FramedImage
          height={200}
          label={c.softCloseLabel}
          sublabel={c.softCloseSublabel}
          shadow={c.softCloseShadow}
        >
          <img
            src={c.softCloseImage}
            alt={c.softCloseAlt}
            style={{ width: "100%", height: 200, objectFit: "cover", display: "block" }}
          />
        </FramedImage>
      </div>

      {/* 26. Signoff (Lena Bauer, long variant) */}
      <Signoff bg={BG_CTA} />

      {/* 27. Footer */}
      <Footer />
    </EmailShell>
  );
};

Object.assign(window, { Email1, Email2, Email3, Email4, Email5, Email6, Email7, Email8 });